import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
  TrendingUp, FileText, Map, LogIn, LogOut, User,
  Menu, X, Home, Info, Phone, BookOpen,
  Shield, ChevronRight, Sparkles, Mail, FileCheck,
  GraduationCap, Award, Route, Building2
} from 'lucide-react'
import { AuthProvider, useAuth } from './hooks/useAuth.jsx'
import { ThemeProvider } from './hooks/useTheme.jsx'
import ThemeToggle from './components/ThemeToggle.jsx'
import ErrorBoundary from './components/ErrorBoundary.jsx'
import LandingPage from './components/LandingPage.jsx'
import ResumeAnalyzer from './components/ResumeAnalyzer.jsx'
import Hero from './components/Hero.jsx'
import Heatmap from './components/Heatmap.jsx'
import ModeSelector from './components/ModeSelector.jsx'
import CollegeVsCorporate from './components/CollegeVsCorporate.jsx'
import WaveBg from './components/WaveBg.jsx'
import CertCompare from './components/CertCompare.jsx'
import CareerSimulator from './components/CareerSimulator.jsx'
import JobCertMap from './components/JobCertMap.jsx'

const T = { duration: 0.32, ease: [0.4, 0, 0.2, 1] }

const hs = {
  fontFamily: 'Plus Jakarta Sans, sans-serif',
  fontWeight: '800', letterSpacing: '-0.02em',
  color: 'var(--text)', lineHeight: 1.05, marginBottom: '24px',
}

const PageWrapper = function({ children, maxWidth, padding }) {
  return (
    <div style={{ position: 'relative', minHeight: '100vh' }}>
      <WaveBg variant="app" />
      <div style={{ maxWidth: maxWidth || '800px', margin: '0 auto', padding: padding || '88px 24px 60px', position: 'relative', zIndex: 1 }}>
        {children}
      </div>
    </div>
  )
}

const AboutPage = function() {
  return (
    <PageWrapper maxWidth="800px">
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={T}>
        <h1 style={{ ...hs, fontSize: 'clamp(2.5rem,6vw,4rem)' }}>
          WHY WE BUILT<br /><span style={{ color: 'var(--indigo)' }}>CERTIFYROI</span>
        </h1>
        <div className="glass" style={{ padding: '32px', marginBottom: '20px' }}>
          <p style={{ fontSize: '15px', color: 'var(--text-2)', lineHeight: '1.8', marginBottom: '16px', fontFamily: 'Inter, sans-serif' }}>
            CertifyROI was born from one frustration: every career site tells you what certifications exist, but nobody tells you whether it is worth your money.
          </p>
          <p style={{ fontSize: '15px', color: 'var(--text-2)', lineHeight: '1.8', fontFamily: 'Inter, sans-serif' }}>
            We built this for the anxious 26-year-old scrolling LinkedIn at 11pm, the ops manager wanting to switch into data, and the fresh graduate who just wants their first offer.
          </p>
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(180px,1fr))', gap: '14px' }}>
          {[
            { icon: '🎯', title: 'Mission',      desc: 'Turn career anxiety into confident data-backed decisions.' },
            { icon: '📊', title: 'Data Sources', desc: 'LinkedIn, NASSCOM, Naukri, AmbitionBox, WEF 2026.' },
            { icon: '🤖', title: 'AI Engine',    desc: 'Groq llama-3.3-70b. Fastest AI inference, under 2 seconds.' },
            { icon: '🌏', title: 'India First',  desc: 'Built for Bangalore, Hyderabad, Pune, Mumbai, Delhi, Chennai.' },
          ].map(function(c, i) {
            return (
              <div key={i} className="glass" style={{ padding: '20px' }}>
                <div style={{ fontSize: '1.8rem', marginBottom: '10px' }}>{c.icon}</div>
                <h3 style={{ fontSize: '14px', color: 'var(--text)', marginBottom: '6px', fontFamily: 'Plus Jakarta Sans, sans-serif', fontWeight: '700' }}>{c.title}</h3>
                <p style={{ fontSize: '13px', color: 'var(--text-3)', lineHeight: '1.6', fontFamily: 'Inter, sans-serif' }}>{c.desc}</p>
              </div>
            )
          })}
        </div>
      </motion.div>
    </PageWrapper>
  )
}

const TermsPage = function() {
  return (
    <PageWrapper maxWidth="780px">
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={T}>
        <h1 style={{ ...hs, fontSize: 'clamp(2rem,5vw,3.5rem)' }}>TERMS AND<br /><span style={{ color: 'var(--indigo)' }}>CONDITIONS</span></h1>
        {[
          { title: '1. Acceptance', body: 'By using CertifyROI, you agree to these terms. We may update them at any time.' },
          { title: '2. Educational Purpose', body: 'All ROI projections are approximations for educational purposes only, not financial advice. Always verify with a qualified career advisor.' },
          { title: '3. AI Disclaimer', body: 'AI-powered analysis is generated by large language models. Results may be inaccurate. Verify all data before making career decisions.' },
          { title: '4. Data and Privacy', body: 'Resume text is processed in real-time and not stored. We do not sell personal data. See our Privacy Policy for full details.' },
          { title: '5. Salary Data', body: 'Salary figures are sourced from public reports including NASSCOM, LinkedIn India, and Naukri. These are median estimates and may not reflect individual experiences.' },
          { title: '6. Limitation of Liability', body: 'CertifyROI is not liable for career decisions made based on information on this platform.' },
          { title: '7. Contact', body: 'Questions? Email us at hello@certifyroi.in' },
        ].map(function(s, i) {
          return (
            <div key={i} className="glass" style={{ padding: '20px', marginBottom: '10px' }}>
              <h3 style={{ fontSize: '14px', color: 'var(--text)', fontFamily: 'Plus Jakarta Sans, sans-serif', fontWeight: '700', marginBottom: '6px' }}>{s.title}</h3>
              <p style={{ fontSize: '13px', color: 'var(--text-3)', lineHeight: '1.7', fontFamily: 'Inter, sans-serif' }}>{s.body}</p>
            </div>
          )
        })}
        <p style={{ fontSize: '11px', color: 'var(--text-4)', marginTop: '16px', textAlign: 'center', fontFamily: 'Inter, sans-serif' }}>Last updated: March 2026</p>
      </motion.div>
    </PageWrapper>
  )
}

const PrivacyPage = function() {
  return (
    <PageWrapper maxWidth="780px">
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={T}>
        <h1 style={{ ...hs, fontSize: 'clamp(2rem,5vw,3.5rem)' }}>PRIVACY<br /><span style={{ color: 'var(--indigo)' }}>POLICY</span></h1>
        {[
          { title: 'What we collect', body: 'Email address (if you sign in with Google) and anonymised usage data. Resume text is NOT stored — processed in real-time and immediately discarded after analysis.' },
          { title: 'How we use your data', body: 'Email is used for authentication only. We do not send marketing emails unless you explicitly opt in. Usage data helps us improve the product.' },
          { title: 'Cookies and storage', body: 'Essential cookies for authentication. We use localStorage to save your calculator preferences locally on your device. No third-party advertising cookies.' },
          { title: 'Third-party services', body: 'Groq (AI inference — text not stored), Firebase (authentication + profile storage), Vercel (hosting and edge functions).' },
          { title: 'Your rights', body: 'You can request deletion of your data at any time by emailing hello@certifyroi.in. Requests are processed within 7 business days.' },
          { title: 'Contact', body: 'Privacy questions? Email hello@certifyroi.in' },
        ].map(function(s, i) {
          return (
            <div key={i} className="glass" style={{ padding: '20px', marginBottom: '10px' }}>
              <h3 style={{ fontSize: '14px', color: 'var(--text)', fontFamily: 'Plus Jakarta Sans, sans-serif', fontWeight: '700', marginBottom: '6px' }}>{s.title}</h3>
              <p style={{ fontSize: '13px', color: 'var(--text-3)', lineHeight: '1.7', fontFamily: 'Inter, sans-serif' }}>{s.body}</p>
            </div>
          )
        })}
      </motion.div>
    </PageWrapper>
  )
}

const BLOG_POSTS = [
  { id: 1, tag: 'Cloud',        tagColor: '#6366F1', title: 'Is AWS Solutions Architect Worth It in 2026?',           excerpt: 'With 2,400+ open roles on Naukri and average hikes of 30-40%, AWS SAA remains the highest-ROI cert for Indian engineers. But market saturation is real.', readTime: '4 min', date: 'Mar 2026', forWho: 'Professional' },
  { id: 2, tag: 'Career Switch', tagColor: '#F59E0B', title: 'From Ops Manager to Data Analyst: A 6-Month Plan',        excerpt: 'Three real people. Three backgrounds. One goal: break into data from operations. What certifications actually bridged the gap.',                           readTime: '6 min', date: 'Feb 2026', forWho: 'Switcher'     },
  { id: 3, tag: 'Student',       tagColor: '#818CF8', title: "Fresher Guide to First Offer in India 2026",               excerpt: 'No experience. No salary history. But you can get a strong first offer in 5-8 months with the right cert and portfolio strategy.',                        readTime: '8 min', date: 'Feb 2026', forWho: 'Student'      },
  { id: 4, tag: 'Management',    tagColor: '#10B981', title: 'PMP vs CSM: Which Pays More in India?',                    excerpt: 'Both are management certs but target completely different markets. We ran the ROI numbers for Bangalore, Hyderabad, and Delhi NCR.',                   readTime: '5 min', date: 'Jan 2026', forWho: 'Professional' },
  { id: 5, tag: 'Finance',       tagColor: '#34D399', title: 'Best Finance Certifications for Indian Professionals 2026', excerpt: 'CFA, FMVA, or CPA? We break down which finance cert gives the best ROI for Indian banking and startup finance professionals.',                        readTime: '6 min', date: 'Dec 2025', forWho: 'Professional' },
]

const BlogPage = function() {
  const [filter, setFilter] = useState('All')
  const filtered = filter === 'All' ? BLOG_POSTS : BLOG_POSTS.filter(function(p) { return p.forWho === filter })
  return (
    <PageWrapper maxWidth="1000px">
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={T}>
        <h1 style={{ ...hs, fontSize: 'clamp(2.5rem,6vw,4rem)' }}>THE CERTIFYROI<br /><span style={{ color: 'var(--indigo)' }}>BLOG</span></h1>
        <p style={{ fontSize: '15px', color: 'var(--text-3)', marginBottom: '28px', fontFamily: 'Inter, sans-serif' }}>Data-driven career guides for Indian tech professionals.</p>
        <div style={{ display: 'flex', gap: '8px', marginBottom: '28px', flexWrap: 'wrap' }}>
          {['All','Student','Switcher','Professional'].map(function(t) {
            return (
              <button key={t} onClick={function() { setFilter(t) }}
                style={{ padding: '6px 16px', borderRadius: '20px', fontSize: '13px', cursor: 'pointer', fontFamily: 'Inter, sans-serif', fontWeight: '600', transition: 'all 0.18s', background: filter===t?'var(--indigo-dim)':'var(--surface)', border: '1px solid '+(filter===t?'var(--border-accent)':'var(--border)'), color: filter===t?'var(--indigo-light)':'var(--text-4)' }}>
                {t}
              </button>
            )
          })}
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(290px,1fr))', gap: '16px' }}>
          {filtered.map(function(post, i) {
            return (
              <motion.div key={post.id} initial={{ opacity:0, y:14 }} animate={{ opacity:1, y:0 }} transition={{ delay:i*0.07 }} className="glass"
                style={{ padding:'22px', cursor:'pointer', display:'flex', flexDirection:'column' }} whileHover={{ y:-3 }}
                onClick={function() { alert(post.title+'\n\nFull post coming soon!') }}>
                <div style={{ fontSize:'10px', fontWeight:'700', padding:'3px 8px', borderRadius:'6px', background:post.tagColor+'18', color:post.tagColor, display:'inline-block', marginBottom:'12px', fontFamily:'JetBrains Mono, monospace', letterSpacing:'0.06em' }}>{post.tag}</div>
                <h3 style={{ fontSize:'14px', fontWeight:'700', color:'var(--text)', marginBottom:'8px', lineHeight:'1.4', fontFamily:'Plus Jakarta Sans, sans-serif', flex:1 }}>{post.title}</h3>
                <p style={{ fontSize:'12px', color:'var(--text-3)', lineHeight:'1.65', marginBottom:'16px', fontFamily:'Inter, sans-serif' }}>{post.excerpt}</p>
                <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginTop:'auto' }}>
                  <span style={{ fontSize:'11px', color:'var(--text-4)', fontFamily:'Inter, sans-serif' }}>{post.date} · {post.readTime} read</span>
                  <span style={{ fontSize:'12px', color:'var(--indigo)', fontWeight:'700', fontFamily:'Plus Jakarta Sans, sans-serif', display:'flex', alignItems:'center', gap:'3px' }}>Read <ChevronRight size={12} /></span>
                </div>
              </motion.div>
            )
          })}
        </div>
      </motion.div>
    </PageWrapper>
  )
}

const FAQPage = function() {
  const [open, setOpen] = useState(null)
  const faqs = [
    { q:'Is CertifyROI free?', a:'Yes. The ROI calculator, heatmap, city demand data, and career simulator are all free. You get 3 free AI analyses as a guest. Sign in with Google for unlimited free AI analyses.' },
    { q:'How accurate are the salary figures?', a:'Sourced from LinkedIn Economic Graph, NASSCOM 2025, Naukri salary reports, and AmbitionBox. Figures are medians — individual results vary by city, company, and negotiation skill.' },
    { q:'Is my resume stored anywhere?', a:'No. Resume text is processed in real-time and immediately discarded after analysis. It is never stored, logged, or shared with any third party.' },
    { q:'What is the difference between Resume AI and ROI Calculator?', a:'Resume AI is for discovery — you do not know which cert to pursue. It reads your background and recommends the top 3 certs. ROI Calculator is for validation — you know which cert and want to see the exact financial numbers.' },
    { q:'Why does Student Mode exist?', a:'Standard ROI calculators assume you have a salary to compare against. Students do not. Student Mode reframes everything around time-to-first-offer, fresher benchmarks, and career investment ROI instead of salary hike percentage.' },
    { q:'Can I use this for non-tech careers?', a:'Yes. Finance (CFA, FMVA, CA), Marketing (Google, HubSpot), HR (SHRM), Product Management, UX Design, Supply Chain (APICS), Architecture (LEED), Medical (DNB, USMLE), Law (CS, Bar), and Government exam prep are all covered.' },
    { q:'Is this only for Bangalore?', a:'No. CertifyROI covers Bangalore, Hyderabad, Pune, Mumbai, Delhi NCR, Chennai, Kolkata, and Ahmedabad with city-specific salary benchmarks and demand data.' },
    { q:'What is the Cert to Job Map?', a:'It shows exactly which certifications are required or preferred for specific roles — from UPSC/SSC/PSU government positions to internal promotions at TCS, Infosys, Deloitte, and HDFC Bank. Government data is from official notifications. Private company data is employee-reported.' },
  ]
  return (
    <PageWrapper maxWidth="740px">
      <motion.div initial={{ opacity:0, y:20 }} animate={{ opacity:1, y:0 }} transition={T}>
        <h1 style={{ ...hs, fontSize:'clamp(2.5rem,6vw,4rem)' }}>FREQUENTLY<br /><span style={{ color:'var(--indigo)' }}>ASKED</span></h1>
        <p style={{ fontSize:'15px', color:'var(--text-3)', marginBottom:'28px', fontFamily:'Inter, sans-serif' }}>Everything you wanted to know about CertifyROI.</p>
        <div style={{ display:'flex', flexDirection:'column', gap:'8px' }}>
          {faqs.map(function(faq, i) {
            return (
              <motion.div key={i} className="glass" initial={{ opacity:0, y:8 }} animate={{ opacity:1, y:0 }} transition={{ delay:i*0.04 }}
                style={{ overflow:'hidden', cursor:'pointer' }} onClick={function() { setOpen(open===i?null:i) }}>
                <div style={{ padding:'16px 20px', display:'flex', alignItems:'center', justifyContent:'space-between', gap:'12px' }}>
                  <span style={{ fontSize:'14px', fontWeight:'600', color:open===i?'var(--indigo-light)':'var(--text)', fontFamily:'Plus Jakarta Sans, sans-serif', lineHeight:'1.4' }}>{faq.q}</span>
                  <ChevronRight size={15} color="var(--text-4)" style={{ flexShrink:0, transform:open===i?'rotate(90deg)':'none', transition:'transform 0.2s' }} />
                </div>
                <AnimatePresence>
                  {open===i ? (
                    <motion.div initial={{ height:0, opacity:0 }} animate={{ height:'auto', opacity:1 }} exit={{ height:0, opacity:0 }} transition={{ duration:0.22 }} style={{ overflow:'hidden' }}>
                      <div style={{ padding:'0 20px 18px', paddingTop:'4px', fontSize:'14px', color:'var(--text-2)', borderTop:'1px solid var(--border)', paddingTop:'12px', fontFamily:'Inter, sans-serif', lineHeight:'1.75' }}>{faq.a}</div>
                    </motion.div>
                  ) : null}
                </AnimatePresence>
              </motion.div>
            )
          })}
        </div>
      </motion.div>
    </PageWrapper>
  )
}

const ContactPage = function() {
  const [sent, setSent] = useState(false)
  const [formData, setFormData] = useState({ name:'', email:'', subject:'General feedback', message:'' })
  const inputStyle = { width:'100%', padding:'11px 14px', background:'var(--surface)', border:'1px solid var(--border)', borderRadius:'10px', color:'var(--text)', fontSize:'14px', fontFamily:'Inter, sans-serif', outline:'none', boxSizing:'border-box', transition:'border-color 0.18s' }
  const labelStyle = { fontSize:'11px', color:'var(--text-4)', display:'block', marginBottom:'6px', textTransform:'uppercase', letterSpacing:'0.08em', fontFamily:'JetBrains Mono, monospace' }
  return (
    <PageWrapper maxWidth="600px">
      <motion.div initial={{ opacity:0, y:20 }} animate={{ opacity:1, y:0 }} transition={T}>
        <h1 style={{ ...hs, fontSize:'clamp(2.5rem,6vw,4rem)' }}>CONTACT<br /><span style={{ color:'var(--indigo)' }}>US</span></h1>
        <p style={{ fontSize:'15px', color:'var(--text-3)', marginBottom:'28px', fontFamily:'Inter, sans-serif' }}>Feedback, bug reports, partnership enquiries, or just saying hi.</p>
        {sent ? (
          <div className="glass" style={{ padding:'48px', textAlign:'center' }}>
            <div style={{ fontSize:'3.5rem', marginBottom:'16px' }}>✅</div>
            <h3 style={{ fontSize:'1.4rem', color:'var(--text)', fontFamily:'Plus Jakarta Sans, sans-serif', fontWeight:'800', marginBottom:'8px' }}>Message Sent!</h3>
            <p style={{ fontSize:'14px', color:'var(--text-3)', fontFamily:'Inter, sans-serif', lineHeight:'1.6' }}>We will reply within 48 hours at the email you provided.</p>
          </div>
        ) : (
          <div className="glass" style={{ padding:'32px' }}>
            <div style={{ marginBottom:'16px' }}>
              <label style={labelStyle}>Name</label>
              <input type="text" placeholder="Your name" value={formData.name}
                onChange={function(e) { setFormData(function(p) { return {...p,name:e.target.value} }) }}
                style={inputStyle}
                onFocus={function(e) { e.target.style.borderColor='var(--border-accent)' }}
                onBlur={function(e)  { e.target.style.borderColor='var(--border)' }} />
            </div>
            <div style={{ marginBottom:'16px' }}>
              <label style={labelStyle}>Email</label>
              <input type="email" placeholder="you@email.com" value={formData.email}
                onChange={function(e) { setFormData(function(p) { return {...p,email:e.target.value} }) }}
                style={inputStyle}
                onFocus={function(e) { e.target.style.borderColor='var(--border-accent)' }}
                onBlur={function(e)  { e.target.style.borderColor='var(--border)' }} />
            </div>
            <div style={{ marginBottom:'16px' }}>
              <label style={labelStyle}>Subject</label>
              <select value={formData.subject} onChange={function(e) { setFormData(function(p) { return {...p,subject:e.target.value} }) }}
                style={{ ...inputStyle, background:'var(--surface)' }}>
                <option>General feedback</option>
                <option>Bug report</option>
                <option>Partnership / B2B</option>
                <option>Data correction</option>
                <option>Press enquiry</option>
              </select>
            </div>
            <div style={{ marginBottom:'24px' }}>
              <label style={labelStyle}>Message</label>
              <textarea rows={5} placeholder="Tell us what is on your mind..." value={formData.message}
                onChange={function(e) { setFormData(function(p) { return {...p,message:e.target.value} }) }}
                style={{ ...inputStyle, resize:'vertical', lineHeight:'1.6' }}
                onFocus={function(e) { e.target.style.borderColor='var(--border-accent)' }}
                onBlur={function(e)  { e.target.style.borderColor='var(--border)' }} />
            </div>
            <button className="btn-primary" style={{ width:'100%', padding:'14px' }} onClick={function() { setSent(true) }}>Send Message</button>
          </div>
        )}
      </motion.div>
    </PageWrapper>
  )
}

const NAV_LINKS = [
  { id:'home',    label:'Home',    icon:Home       },
  { id:'app',     label:'Tools',   icon:TrendingUp },
  { id:'blog',    label:'Blog',    icon:BookOpen   },
  { id:'faq',     label:'FAQ',     icon:Sparkles   },
  { id:'about',   label:'About',   icon:Info       },
  { id:'contact', label:'Contact', icon:Phone      },
]

const STEP_TABS = [
  { id:'resume',     num:'1', label:'Find Cert',     icon:FileText,   desc:'AI picks from resume'    },
  { id:'calculator', num:'2', label:'Calculate ROI', icon:TrendingUp, desc:'Break-even and 5yr gain' },
  { id:'heatmap',    num:'3', label:'City Demand',   icon:Map,        desc:'Is it hot in your city?' },
]

const TOOL_TABS = [
  { id:'compare',  label:'Compare Certs',   icon:Award,         desc:'Two certs side by side'       },
  { id:'simulate', label:'Career Path',     icon:Route,         desc:'Multi-cert salary trajectory' },
  { id:'jobmap',   label:'Cert to Job Map', icon:Building2,     desc:'Which cert gets which role'   },
  { id:'college',  label:'Degree vs Certs', icon:GraduationCap, desc:'MBA vs certifications'        },
]

const ALL_TABS = [...STEP_TABS, ...TOOL_TABS]

// Animated arrow connector between steps
const StepArrow = function({ active }) {
  return (
    <div style={{ display:'flex', alignItems:'center', flexShrink:0, padding:'0 2px' }}>
      <svg width="32" height="16" viewBox="0 0 32 16" fill="none">
        <path
          d="M0 8 H26 M20 2 L28 8 L20 14"
          stroke={active ? '#6366F1' : 'rgba(99,102,241,0.3)'}
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeDasharray={active ? '0' : '4 3'}
          style={{ transition: 'stroke 0.3s' }}
        />
      </svg>
    </div>
  )
}

const NavBar = function({ currentPage, activeTab, onNavigate, onTabChange }) {
  const [menuOpen,  setMenuOpen]  = useState(false)
  const [signingIn, setSigningIn] = useState(false)
  const { user, signInGoogle, signOut, loading } = useAuth()

  const go        = function(id)  { onNavigate(id); setMenuOpen(false) }
  const switchTab = function(id)  { onTabChange(id) }

  const handleSignIn = async function() {
    setSigningIn(true)
    try { await signInGoogle() } catch(e) {}
    setSigningIn(false)
  }

  const NAV_H  = 64
  const TABS_H = 88   // two rows: 44px + 44px

  return (
    <>
      <motion.header initial={{ y:-20, opacity:0 }} animate={{ y:0, opacity:1 }} transition={T}
        style={{ position:'fixed', top:0, left:0, right:0, zIndex:100, background:'var(--bg)', backdropFilter:'blur(20px)', WebkitBackdropFilter:'blur(20px)', borderBottom:'1px solid var(--border)', transition:'background 0.3s' }}>

        {/* ── Main nav row ── */}
        <div style={{ maxWidth:'1240px', margin:'0 auto', padding:'0 16px' }}>
          <div style={{ display:'flex', alignItems:'center', height:NAV_H+'px', gap:'4px' }}>

            <button onClick={function() { go('home') }}
              style={{ background:'none', border:'none', cursor:'pointer', display:'flex', alignItems:'center', gap:'8px', flexShrink:0, padding:'0 8px 0 0', marginRight:'8px' }}>
              <div style={{ width:'30px', height:'30px', background:'linear-gradient(135deg,var(--indigo),#4338CA)', borderRadius:'8px', display:'flex', alignItems:'center', justifyContent:'center' }}>
                <TrendingUp size={15} color="white" />
              </div>
              <span style={{ fontFamily:'Plus Jakarta Sans, sans-serif', fontWeight:'800', fontSize:'17px', letterSpacing:'-0.02em', color:'var(--text)' }}>
                Certify<span style={{ color:'var(--indigo)' }}>ROI</span>
              </span>
            </button>

            <nav style={{ display:'flex', gap:'2px', flex:1, justifyContent:'center', alignItems:'center' }}>
              {NAV_LINKS.map(function(link) {
                const isActive = currentPage === link.id
                return (
                  <button key={link.id} onClick={function() { go(link.id) }}
                    style={{ display:'flex', alignItems:'center', gap:'5px', padding:'7px 14px', borderRadius:'8px', border:'1px solid '+(isActive?'var(--border-accent)':'transparent'), background:isActive?'var(--indigo-dim)':'transparent', color:isActive?'var(--indigo-light)':'var(--text-4)', fontSize:'13px', fontWeight:isActive?'700':'500', cursor:'pointer', fontFamily:'Plus Jakarta Sans, sans-serif', whiteSpace:'nowrap', transition:'all 0.18s', letterSpacing:'-0.01em' }}>
                    <link.icon size={12} />{link.label}
                  </button>
                )
              })}
            </nav>

            <div style={{ display:'flex', alignItems:'center', gap:'6px', flexShrink:0, marginLeft:'auto' }}>
              {!loading ? (
                user ? (
                  <div style={{ display:'flex', alignItems:'center', gap:'6px' }}>
                    {user.photoURL
                      ? <img src={user.photoURL} alt="" style={{ width:'28px', height:'28px', borderRadius:'50%', border:'2px solid var(--border-accent)' }} />
                      : <div style={{ width:'28px', height:'28px', borderRadius:'50%', background:'linear-gradient(135deg,var(--indigo),#10B981)', display:'flex', alignItems:'center', justifyContent:'center' }}><User size={13} color="white" /></div>
                    }
                    <button onClick={signOut} style={{ background:'rgba(239,68,68,0.1)', border:'1px solid rgba(239,68,68,0.2)', borderRadius:'7px', color:'#EF4444', fontSize:'12px', padding:'5px 10px', cursor:'pointer', display:'flex', alignItems:'center', gap:'4px', fontFamily:'Inter, sans-serif' }}>
                      <LogOut size={12} /> <span className="signout-text">Sign out</span>
                    </button>
                  </div>
                ) : (
                  <button onClick={handleSignIn} disabled={signingIn}
                    style={{ display:'flex', alignItems:'center', gap:'5px', background:'var(--indigo)', border:'none', borderRadius:'8px', padding:'7px 14px', cursor:'pointer', color:'white', fontSize:'13px', fontFamily:'Inter, sans-serif', fontWeight:'600', opacity:signingIn?0.7:1 }}>
                    <LogIn size={13} /><span className="signin-text">{signingIn?'...':'Sign in'}</span>
                  </button>
                )
              ) : null}
              <ThemeToggle />
              <button onClick={function() { setMenuOpen(function(v) { return !v }) }}
                style={{ background:'var(--surface)', border:'1px solid var(--border)', borderRadius:'7px', padding:'7px', cursor:'pointer', color:'var(--text-3)', display:'flex', alignItems:'center', transition:'all 0.18s' }}>
                {menuOpen ? <X size={15} /> : <Menu size={15} />}
              </button>
            </div>
          </div>
        </div>

        {/* ── Two-row tab bar ── */}
        {currentPage === 'app' ? (
          <div>

            {/* Row 1: Steps with flow arrows */}
            <div style={{ borderTop:'1px solid var(--border)', background:'var(--bg)' }}>
              <div style={{ maxWidth:'1240px', margin:'0 auto', padding:'0 24px', display:'flex', alignItems:'center', justifyContent:'center', height:'46px', gap:'0' }}>

                {/* Step label */}
                <div style={{ fontSize:'9px', color:'var(--text-4)', fontFamily:"'JetBrains Mono', monospace", textTransform:'uppercase', letterSpacing:'0.12em', marginRight:'16px', flexShrink:0, whiteSpace:'nowrap' }}>
                  Core Flow
                </div>

                {/* Step tabs with arrows */}
                {STEP_TABS.map(function(tab, i) {
                  const active = activeTab === tab.id
                  const prevActive = i > 0 && activeTab === STEP_TABS[i-1].id
                  const isCompleted = STEP_TABS.findIndex(function(t) { return t.id === activeTab }) > i
                  return (
                    <div key={tab.id} style={{ display:'flex', alignItems:'center' }}>
                      {i > 0 ? <StepArrow active={isCompleted || (activeTab === tab.id)} /> : null}
                      <button onClick={function() { switchTab(tab.id) }}
                        style={{ display:'flex', alignItems:'center', gap:'7px', padding:'6px 14px', borderRadius:'8px', border:'1px solid '+(active?'var(--border-accent)':'transparent'), background:active?'var(--indigo-dim)':'transparent', color:active?'var(--indigo-light)':isCompleted?'rgba(99,102,241,0.5)':'var(--text-3)', cursor:'pointer', fontFamily:"'Plus Jakarta Sans', sans-serif", transition:'all 0.2s', whiteSpace:'nowrap', flexShrink:0 }}>
                        {/* Step number bubble */}
                        <div style={{ width:'18px', height:'18px', borderRadius:'50%', background:active?'var(--indigo)':isCompleted?'rgba(99,102,241,0.3)':'var(--surface)', border:'1px solid '+(active?'var(--indigo)':isCompleted?'rgba(99,102,241,0.4)':'var(--border)'), display:'flex', alignItems:'center', justifyContent:'center', fontSize:'10px', fontWeight:'700', color:active?'white':isCompleted?'var(--indigo-light)':'var(--text-4)', flexShrink:0, transition:'all 0.2s', fontFamily:"'JetBrains Mono', monospace" }}>
                          {tab.num}
                        </div>
                        <tab.icon size={12} />
                        <span style={{ fontSize:'13px', fontWeight:active?'700':'500', letterSpacing:'-0.01em' }}>{tab.label}</span>
                      </button>
                    </div>
                  )
                })}
              </div>
            </div>

            {/* Row 2: Extra tools — centered, same width approach */}
            <div style={{ borderTop:'1px solid rgba(99,102,241,0.08)', background:'rgba(99,102,241,0.02)' }}>
              <div style={{ maxWidth:'1240px', margin:'0 auto', padding:'0 24px', display:'flex', alignItems:'center', justifyContent:'center', height:'40px', gap:'2px' }}>

                <div style={{ fontSize:'9px', color:'var(--text-4)', fontFamily:"'JetBrains Mono', monospace", textTransform:'uppercase', letterSpacing:'0.12em', marginRight:'16px', flexShrink:0, opacity:0.7, whiteSpace:'nowrap' }}>
                  Tools
                </div>

                {TOOL_TABS.map(function(tab) {
                  const active = activeTab === tab.id
                  return (
                    <button key={tab.id} onClick={function() { switchTab(tab.id) }}
                      style={{ display:'flex', alignItems:'center', gap:'5px', padding:'5px 12px', borderRadius:'6px', border:'none', borderBottom:'2px solid '+(active?'var(--indigo)':'transparent'), background:active?'rgba(99,102,241,0.07)':'transparent', color:active?'var(--indigo-light)':'var(--text-4)', fontSize:'12px', fontWeight:active?'700':'400', cursor:'pointer', fontFamily:"'Plus Jakarta Sans', sans-serif", transition:'all 0.2s', whiteSpace:'nowrap', flexShrink:0, letterSpacing:'-0.01em', height:'100%' }}>
                      <tab.icon size={12} />{tab.label}
                    </button>
                  )
                })}

              </div>
            </div>

          </div>
        ) : null}
      </motion.header>

      {/* Hamburger */}
      <AnimatePresence>
        {menuOpen ? (
          <motion.div initial={{ opacity:0, y:-8 }} animate={{ opacity:1, y:0 }} exit={{ opacity:0, y:-8 }} transition={{ duration:0.2 }}
            style={{ position:'fixed', top:(currentPage==='app'?NAV_H+TABS_H:NAV_H)+'px', left:0, right:0, zIndex:99, background:'var(--bg)', backdropFilter:'blur(20px)', borderBottom:'1px solid var(--border)', padding:'20px 16px' }}>
            <div style={{ maxWidth:'1240px', margin:'0 auto' }}>
              <div style={{ fontSize:'10px', color:'var(--text-4)', textTransform:'uppercase', letterSpacing:'0.1em', marginBottom:'10px', fontFamily:'JetBrains Mono, monospace' }}>All Tools</div>
              <div style={{ display:'grid', gridTemplateColumns:'repeat(auto-fill,minmax(150px,1fr))', gap:'8px', marginBottom:'20px' }}>
                {ALL_TABS.map(function(tab) {
                  const isActive = activeTab === tab.id && currentPage === 'app'
                  return (
                    <button key={tab.id} onClick={function() { go('app'); switchTab(tab.id) }}
                      style={{ padding:'14px 12px', borderRadius:'10px', cursor:'pointer', textAlign:'left', background:isActive?'var(--indigo-dim)':'var(--surface)', border:'1px solid '+(isActive?'var(--border-accent)':'var(--border)'), transition:'all 0.18s' }}>
                      <tab.icon size={16} color={isActive?'var(--indigo)':'var(--text-4)'} style={{ marginBottom:'6px', display:'block' }} />
                      <div style={{ fontSize:'12px', fontWeight:'700', color:isActive?'var(--indigo-light)':'var(--text)', marginBottom:'2px', fontFamily:'Plus Jakarta Sans, sans-serif' }}>
                        {'num' in tab ? tab.num+'. '+tab.label : tab.label}
                      </div>
                      <div style={{ fontSize:'11px', color:'var(--text-4)', fontFamily:'Inter, sans-serif' }}>{tab.desc}</div>
                    </button>
                  )
                })}
              </div>
              <div style={{ display:'grid', gridTemplateColumns:'repeat(auto-fill,minmax(120px,1fr))', gap:'6px' }}>
                {[
                  { id:'blog',    label:'Blog',    icon:BookOpen  },
                  { id:'faq',     label:'FAQ',     icon:Sparkles  },
                  { id:'about',   label:'About',   icon:Info      },
                  { id:'contact', label:'Contact', icon:Phone     },
                  { id:'terms',   label:'Terms',   icon:FileCheck },
                  { id:'privacy', label:'Privacy', icon:Shield    },
                ].map(function(item) {
                  return (
                    <button key={item.id} onClick={function() { go(item.id) }}
                      style={{ padding:'10px 12px', borderRadius:'8px', background:'var(--surface)', border:'1px solid var(--border)', cursor:'pointer', display:'flex', alignItems:'center', gap:'7px', color:'var(--text-2)', fontSize:'12px', fontFamily:'Inter, sans-serif', transition:'all 0.18s' }}>
                      <item.icon size={12} color="var(--text-4)" />{item.label}
                    </button>
                  )
                })}
              </div>
            </div>
          </motion.div>
        ) : null}
      </AnimatePresence>
    </>
  )
}

const AppPage = function({ activeTab, onTabChange, mode, onModeChange, onCertSelected, prefilledCert, resumeCity, resumeDomain, resumeName }) {
  const NAV_H  = 64
  const TABS_H = 88

  return (
    <div style={{ paddingTop:(NAV_H+TABS_H)+'px', minHeight:'100vh', background:'var(--app-bg)', position:'relative' }}>
      <WaveBg variant="app" />
      <div style={{ position:'relative', zIndex:1 }}>
        <div style={{ maxWidth:'1100px', margin:'0 auto', padding:'20px 20px 0' }}>
          <ModeSelector activeMode={mode} onChange={onModeChange} />
        </div>
        <AnimatePresence mode="wait">
          <motion.div key={activeTab} initial={{ opacity:0, y:10 }} animate={{ opacity:1, y:0 }} exit={{ opacity:0, y:-6 }} transition={T}>
            <div style={{ maxWidth:'1100px', margin:'0 auto', padding:'0 20px 60px' }}>

              {activeTab==='resume' ? (
                <div className="glass" style={{ padding:'28px' }}>
                  <ResumeAnalyzer mode={mode} onCertSelected={function(certName,city,domain,name) { onCertSelected(certName,city,domain,name) }} />
                </div>
              ) : null}

              {activeTab==='calculator' ? (
                <Hero mode={mode} prefilledCert={prefilledCert} resumeName={resumeName} resumeCity={resumeCity} />
              ) : null}

              {activeTab==='heatmap' ? (
                <div className="glass" style={{ padding:'28px' }}>
                  <Heatmap prefilledCity={resumeCity} prefilledDomain={resumeDomain} certName={prefilledCert} resumeName={resumeName} />
                </div>
              ) : null}

              {activeTab==='compare' ? (
                <div className="glass" style={{ padding:'28px' }}>
                  <CertCompare salary={mode==='student'?4.8:8} prefilledCert={prefilledCert} />
                </div>
              ) : null}

              {activeTab==='simulate' ? (
                <div className="glass" style={{ padding:'28px' }}>
                  <CareerSimulator initialSalary={mode==='student'?4.8:8} />
                </div>
              ) : null}

              {activeTab==='jobmap' ? (
                <div className="glass" style={{ padding:'28px' }}>
                  <JobCertMap />
                </div>
              ) : null}

              {activeTab==='college' ? (
                <div className="glass" style={{ padding:'28px' }}>
                  <CollegeVsCorporate />
                </div>
              ) : null}

            </div>
          </motion.div>
        </AnimatePresence>
      </div>
    </div>
  )
}

const Footer = function({ onNavigate }) {
  return (
    <footer style={{ borderTop:'1px solid var(--border)', padding:'48px 24px 28px', marginTop:'auto', background:'var(--bg)' }}>
      <div style={{ maxWidth:'1240px', margin:'0 auto' }}>
        <div style={{ display:'grid', gridTemplateColumns:'2fr 1fr 1fr 1fr', gap:'32px', marginBottom:'40px' }} className="footer-grid">

          {/* Brand */}
          <div>
            <div style={{ display:'flex', alignItems:'center', gap:'8px', marginBottom:'12px' }}>
              <div style={{ width:'28px', height:'28px', background:'linear-gradient(135deg,var(--indigo),#4338CA)', borderRadius:'8px', display:'flex', alignItems:'center', justifyContent:'center' }}>
                <TrendingUp size={14} color="white" />
              </div>
              <span style={{ fontFamily:'Plus Jakarta Sans, sans-serif', fontWeight:'800', fontSize:'16px', color:'var(--text)', letterSpacing:'-0.01em' }}>
                Certify<span style={{ color:'var(--indigo)' }}>ROI</span>
              </span>
            </div>
            <p style={{ fontSize:'13px', color:'var(--text-4)', fontFamily:'Inter, sans-serif', lineHeight:'1.7', maxWidth:'260px', marginBottom:'16px' }}>
              Data-driven certification ROI decisions for India's tech and finance professionals. Built in Bangalore.
            </p>
            <p style={{ fontSize:'11px', color:'var(--text-4)', fontFamily:'JetBrains Mono, monospace', opacity:0.6 }}>
              Data: LinkedIn · NASSCOM · AmbitionBox · Naukri · WEF 2026
            </p>
          </div>

          {/* Tools */}
          <div>
            <div style={{ fontSize:'10px', color:'var(--text-4)', textTransform:'uppercase', letterSpacing:'0.1em', marginBottom:'14px', fontFamily:'JetBrains Mono, monospace' }}>Tools</div>
            {[
              { id:'app', label:'Resume AI',        tab:'resume'     },
              { id:'app', label:'ROI Calculator',   tab:'calculator' },
              { id:'app', label:'City Demand',      tab:'heatmap'    },
              { id:'app', label:'Compare Certs',    tab:'compare'    },
              { id:'app', label:'Career Simulator', tab:'simulate'   },
              { id:'app', label:'Cert to Job Map',  tab:'jobmap'     },
            ].map(function(l) {
              return (
                <button key={l.label} onClick={function() { onNavigate(l.id) }}
                  style={{ display:'block', background:'none', border:'none', color:'var(--text-4)', fontSize:'13px', cursor:'pointer', marginBottom:'8px', fontFamily:'Inter, sans-serif', padding:0, textAlign:'left', transition:'color 0.15s' }}
                  onMouseEnter={function(e) { e.currentTarget.style.color='var(--text)' }}
                  onMouseLeave={function(e) { e.currentTarget.style.color='var(--text-4)' }}>
                  {l.label}
                </button>
              )
            })}
          </div>

          {/* Company */}
          <div>
            <div style={{ fontSize:'10px', color:'var(--text-4)', textTransform:'uppercase', letterSpacing:'0.1em', marginBottom:'14px', fontFamily:'JetBrains Mono, monospace' }}>Company</div>
            {['about','blog','faq','contact'].map(function(id) {
              const label = id.charAt(0).toUpperCase()+id.slice(1)
              return (
                <button key={id} onClick={function() { onNavigate(id) }}
                  style={{ display:'block', background:'none', border:'none', color:'var(--text-4)', fontSize:'13px', cursor:'pointer', marginBottom:'8px', fontFamily:'Inter, sans-serif', padding:0, textAlign:'left', transition:'color 0.15s' }}
                  onMouseEnter={function(e) { e.currentTarget.style.color='var(--text)' }}
                  onMouseLeave={function(e) { e.currentTarget.style.color='var(--text-4)' }}>
                  {label}
                </button>
              )
            })}
          </div>

          {/* Legal */}
          <div>
            <div style={{ fontSize:'10px', color:'var(--text-4)', textTransform:'uppercase', letterSpacing:'0.1em', marginBottom:'14px', fontFamily:'JetBrains Mono, monospace' }}>Legal</div>
            {['terms','privacy'].map(function(id) {
              const label = id.charAt(0).toUpperCase()+id.slice(1)+(id==='terms'?' & Conditions':'')
              return (
                <button key={id} onClick={function() { onNavigate(id) }}
                  style={{ display:'block', background:'none', border:'none', color:'var(--text-4)', fontSize:'13px', cursor:'pointer', marginBottom:'8px', fontFamily:'Inter, sans-serif', padding:0, textAlign:'left', transition:'color 0.15s' }}
                  onMouseEnter={function(e) { e.currentTarget.style.color='var(--text)' }}
                  onMouseLeave={function(e) { e.currentTarget.style.color='var(--text-4)' }}>
                  {label}
                </button>
              )
            })}
            <div style={{ marginTop:'16px', padding:'10px 12px', borderRadius:'8px', background:'var(--indigo-dim)', border:'1px solid var(--border-accent)' }}>
              <div style={{ fontSize:'10px', color:'var(--indigo-light)', fontFamily:'JetBrains Mono, monospace', marginBottom:'4px' }}>CONTACT</div>
              <a href="mailto:hello@certifyroi.in" style={{ fontSize:'12px', color:'var(--text-3)', fontFamily:'Inter, sans-serif', textDecoration:'none' }}>hello@certifyroi.in</a>
            </div>
          </div>

        </div>

        {/* Bottom bar */}
        <div style={{ borderTop:'1px solid var(--border)', paddingTop:'20px', display:'flex', justifyContent:'space-between', flexWrap:'wrap', gap:'8px', alignItems:'center' }}>
          <p style={{ fontSize:'12px', color:'var(--text-4)', fontFamily:'Inter, sans-serif' }}>
            2026 CertifyROI. All rights reserved. Not financial advice.
          </p>
          <p style={{ fontSize:'11px', color:'var(--text-4)', fontFamily:'JetBrains Mono, monospace', opacity:0.5 }}>
            Made with care for India's professionals
          </p>
        </div>
      </div>
    </footer>
  )
}

function AppRoot() {
  const [page,          setPage]          = useState('home')
  const [activeTab,     setActiveTab]     = useState('resume')
  const [mode,          setMode]          = useState('professional')
  const [prefilledCert, setPrefilledCert] = useState('')
  const [resumeCity,    setResumeCity]    = useState('')
  const [resumeDomain,  setResumeDomain]  = useState('')
  const [resumeName,    setResumeName]    = useState('')

  const navigate = function(pageId) { setPage(pageId); window.scrollTo({ top:0, behavior:'smooth' }) }
  const goToApp  = function(tab)    { setActiveTab(tab||'resume'); navigate('app') }

  const handleCertSelected = function(certName, city, domain, name) {
    setPrefilledCert(certName)
    if (city)   setResumeCity(city)
    if (domain) setResumeDomain(domain)
    if (name)   setResumeName(name)
    setActiveTab('calculator')
  }

  const renderPage = function() {
    if (page==='home')    return <LandingPage onEnter={function() { goToApp('resume') }} />
    if (page==='app')     return <AppPage activeTab={activeTab} onTabChange={setActiveTab} mode={mode} onModeChange={setMode} onCertSelected={handleCertSelected} prefilledCert={prefilledCert} resumeCity={resumeCity} resumeDomain={resumeDomain} resumeName={resumeName} />
    if (page==='blog')    return <BlogPage />
    if (page==='faq')     return <FAQPage />
    if (page==='about')   return <AboutPage />
    if (page==='contact') return <ContactPage />
    if (page==='terms')   return <TermsPage />
    if (page==='privacy') return <PrivacyPage />
    return <LandingPage onEnter={function() { goToApp('resume') }} />
  }

  return (
    <div style={{ minHeight:'100vh', display:'flex', flexDirection:'column' }}>
      <NavBar currentPage={page} activeTab={activeTab} onNavigate={navigate} onTabChange={setActiveTab} />
      <main style={{ flex:1 }}>
        <AnimatePresence mode="wait">
          <motion.div key={page+activeTab} initial={{ opacity:0 }} animate={{ opacity:1 }} exit={{ opacity:0 }} transition={T}>
            {renderPage()}
          </motion.div>
        </AnimatePresence>
      </main>
      <Footer onNavigate={navigate} />
    </div>
  )
}

export default function App() {
  return (
    <ErrorBoundary>
      <ThemeProvider>
        <AuthProvider>
          <AppRoot />
        </AuthProvider>
      </ThemeProvider>
    </ErrorBoundary>
  )
}