export const CERTIFICATIONS = [
  {
    id: 'aws-saa',
    name: 'AWS Solutions Architect',
    avgCost: 25000, avgHike: 35, timeMonths: 3,
    demand: 'Very High',
    link: 'https://aws.amazon.com/certification/certified-solutions-architect-associate/',
    affiliate: true,
    tags: ['Cloud', 'Backend', 'DevOps'], domain: 'tech',
    forWho: 'Mid-level engineers moving into cloud/architecture roles',
  },
  {
    id: 'azure-fundamentals',
    name: 'Azure Fundamentals',
    avgCost: 12000, avgHike: 20, timeMonths: 2,
    demand: 'Very High',
    link: 'https://learn.microsoft.com/certifications/azure-fundamentals/',
    affiliate: false,
    tags: ['Cloud', 'Microsoft', 'Entry-level'], domain: 'tech',
    forWho: 'Beginners and freshers entering cloud computing',
  },
  {
    id: 'kubernetes',
    name: 'CKA Kubernetes',
    avgCost: 30000, avgHike: 40, timeMonths: 4,
    demand: 'High',
    link: 'https://training.linuxfoundation.org/certification/certified-kubernetes-administrator-cka/',
    affiliate: false,
    tags: ['DevOps', 'Cloud', 'Containers'], domain: 'tech',
    forWho: 'Backend/DevOps engineers with 2+ yrs wanting infra roles',
  },
  {
    id: 'gcp-data',
    name: 'Google Data Analytics',
    avgCost: 18000, avgHike: 28, timeMonths: 4,
    demand: 'High',
    link: 'https://grow.google/certificates/data-analytics/',
    affiliate: true,
    tags: ['Data', 'Analytics', 'Entry-level'], domain: 'data',
    forWho: 'Career switchers and freshers entering data analytics',
  },
  {
    id: 'tensorflow',
    name: 'TensorFlow Developer',
    avgCost: 20000, avgHike: 45, timeMonths: 5,
    demand: 'Medium',
    link: 'https://www.tensorflow.org/certificate',
    affiliate: false,
    tags: ['ML', 'AI', 'Python'], domain: 'data',
    forWho: 'Python developers transitioning into ML/AI engineering',
  },
  {
    id: 'ibm-data-science',
    name: 'IBM Data Science',
    avgCost: 15000, avgHike: 30, timeMonths: 5,
    demand: 'High',
    link: 'https://www.coursera.org/professional-certificates/ibm-data-science',
    affiliate: false,
    tags: ['Data Science', 'Python', 'ML'], domain: 'data',
    forWho: 'Analysts and engineers wanting a structured data science credential',
  },
  {
    id: 'tableau',
    name: 'Tableau Desktop Specialist',
    avgCost: 25000, avgHike: 22, timeMonths: 2,
    demand: 'High',
    link: 'https://www.tableau.com/learn/certification/desktop-specialist',
    affiliate: false,
    tags: ['Data', 'Visualization', 'Analytics'], domain: 'data',
    forWho: 'Business analysts moving into data viz roles',
  },
  {
    id: 'pmp',
    name: 'PMP Certification',
    avgCost: 55000, avgHike: 30, timeMonths: 6,
    demand: 'High',
    link: 'https://www.pmi.org/certifications/project-management-pmp',
    affiliate: true,
    tags: ['Management', 'Leadership', 'Senior'], domain: 'management',
    forWho: 'Project leads with 3+ yrs targeting senior PM roles',
  },
  {
    id: 'agile-scrum',
    name: 'Certified Scrum Master',
    avgCost: 40000, avgHike: 28, timeMonths: 1,
    demand: 'Very High',
    link: 'https://www.scrumalliance.org/get-certified/scrum-master-track/certified-scrummaster',
    affiliate: false,
    tags: ['Agile', 'Scrum', 'Management'], domain: 'management',
    forWho: 'Team leads moving into agile delivery roles',
  },
  {
    id: 'google-pm',
    name: 'Google Project Management',
    avgCost: 12000, avgHike: 20, timeMonths: 6,
    demand: 'High',
    link: 'https://grow.google/certificates/project-management/',
    affiliate: false,
    tags: ['Business', 'Project Mgmt', 'Entry-level'], domain: 'business',
    forWho: 'Freshers and ops professionals entering PM roles',
  },
  {
    id: 'six-sigma',
    name: 'Six Sigma Green Belt',
    avgCost: 30000, avgHike: 25, timeMonths: 3,
    demand: 'Medium',
    link: 'https://asq.org/cert/six-sigma-green-belt',
    affiliate: false,
    tags: ['Operations', 'Quality', 'Business'], domain: 'business',
    forWho: 'Ops/quality professionals in manufacturing or supply chain',
  },
  {
    id: 'cfa-l1',
    name: 'CFA Level 1',
    avgCost: 60000, avgHike: 35, timeMonths: 6,
    demand: 'High',
    link: 'https://www.cfainstitute.org/en/programs/cfa',
    affiliate: false,
    tags: ['Finance', 'Investment', 'Banking'], domain: 'finance',
    forWho: 'Finance/banking professionals targeting investment roles',
  },
  {
    id: 'fmva',
    name: 'FMVA Financial Modeling',
    avgCost: 20000, avgHike: 28, timeMonths: 3,
    demand: 'High',
    link: 'https://corporatefinanceinstitute.com/certifications/financial-modeling-valuation-analyst-fmva/',
    affiliate: false,
    tags: ['Finance', 'Modeling', 'Excel'], domain: 'finance',
    forWho: 'Finance graduates and analysts wanting valuation skills',
  },
  {
    id: 'google-digital-marketing',
    name: 'Google Digital Marketing',
    avgCost: 8000, avgHike: 22, timeMonths: 3,
    demand: 'High',
    link: 'https://skillshop.google.com/',
    affiliate: false,
    tags: ['Marketing', 'SEO', 'Ads'], domain: 'marketing',
    forWho: 'Freshers and non-tech professionals entering digital marketing',
  },
  {
    id: 'hubspot-marketing',
    name: 'HubSpot Marketing',
    avgCost: 0, avgHike: 18, timeMonths: 1,
    demand: 'Medium',
    link: 'https://academy.hubspot.com/courses/inbound-marketing',
    affiliate: false,
    tags: ['Marketing', 'Inbound', 'CRM', 'Free'], domain: 'marketing',
    forWho: 'Marketing executives — free and fast',
  },
  {
    id: 'comptia-security',
    name: 'CompTIA Security+',
    avgCost: 35000, avgHike: 32, timeMonths: 3,
    demand: 'High',
    link: 'https://www.comptia.org/certifications/security',
    affiliate: false,
    tags: ['Security', 'IT', 'Entry-level'], domain: 'tech',
    forWho: 'IT professionals moving into cybersecurity',
  },
  {
    id: 'ceh',
    name: 'Certified Ethical Hacker',
    avgCost: 50000, avgHike: 38, timeMonths: 4,
    demand: 'High',
    link: 'https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/',
    affiliate: false,
    tags: ['Security', 'Hacking', 'Penetration Testing'], domain: 'tech',
    forWho: 'Network/security engineers targeting offensive security roles',
  },
  {
    id: 'shrm',
    name: 'SHRM-CP (HR)',
    avgCost: 45000, avgHike: 25, timeMonths: 4,
    demand: 'Medium',
    link: 'https://www.shrm.org/credentials/certification/shrm-cp',
    affiliate: false,
    tags: ['HR', 'People Ops', 'Management'], domain: 'hr',
    forWho: 'HR professionals targeting HRBP roles',
  },
  {
    id: 'google-ux',
    name: 'Google UX Design',
    avgCost: 12000, avgHike: 30, timeMonths: 6,
    demand: 'Medium',
    link: 'https://grow.google/certificates/ux-design/',
    affiliate: false,
    tags: ['UX', 'Design', 'Product'], domain: 'design',
    forWho: 'Career switchers entering UX/product design',
  },
  {
    id: 'product-management',
    name: 'Product Management Cert',
    avgCost: 35000, avgHike: 35, timeMonths: 3,
    demand: 'High',
    link: 'https://www.pmschool.io/',
    affiliate: false,
    tags: ['Product', 'PM', 'Tech', 'Strategy'], domain: 'product',
    forWho: 'Engineers and analysts with 2+ yrs wanting to move into PM',
  },
  {
    id: 'apics-cscp',
    name: 'APICS CSCP Supply Chain',
    avgCost: 55000, avgHike: 28, timeMonths: 5,
    demand: 'Medium',
    link: 'https://www.ascm.org/certifications/cscp/',
    affiliate: false,
    tags: ['Supply Chain', 'Operations', 'Logistics'], domain: 'business',
    forWho: 'Ops/logistics professionals targeting supply chain management',
  },
]

export const CERT_DOMAINS = [
  { id: 'all',        label: 'All Domains'    },
  { id: 'tech',       label: 'Tech & Cloud'   },
  { id: 'data',       label: 'Data & AI'      },
  { id: 'management', label: 'Project Mgmt'   },
  { id: 'business',   label: 'Business & Ops' },
  { id: 'finance',    label: 'Finance'        },
  { id: 'marketing',  label: 'Marketing'      },
  { id: 'product',    label: 'Product & UX'   },
  { id: 'design',     label: 'UX & Design'    },
  { id: 'hr',         label: 'HR & People'    },
]

export const GOAL_OPTIONS = [
  { id: 'salary-hike',   label: '💰 Get a salary hike at current job'        },
  { id: 'job-switch',    label: '🔄 Switch to a better company'              },
  { id: 'career-switch', label: '🚀 Switch to a completely different field'  },
  { id: 'first-job',     label: '🎓 Get my first job / fresher offer'        },
  { id: 'promotion',     label: '📈 Get promoted to senior/lead role'        },
  { id: 'freelance',     label: '💼 Start freelancing or consulting'         },
  { id: 'abroad',        label: '✈️  Get a job abroad (US/EU/Singapore)'      },
  { id: 'startup',       label: '⚡ Join or start a startup'                 },
]

export const INDIA_CONTEXT = {
  avgEntryLevel: 480000,
  avgMidLevel:   1200000,
  pgRentAnnual:  180000,
  currency:      '₹',
  cities:        ['Bangalore', 'Hyderabad', 'Pune', 'Mumbai', 'Delhi NCR', 'Chennai'],
}

export const GUEST_FREE_LIMIT = parseInt(import.meta.env.VITE_GUEST_FREE_LIMIT || '3')