// ─────────────────────────────────────────────────────────
// tokens.js — CertifyROI master cert database
// 100+ certifications across all major Indian career domains
// Data: India market 2026 · Sources: Naukri, AmbitionBox,
// NASSCOM, LinkedIn India, respective certification bodies
// ─────────────────────────────────────────────────────────

export const CERTIFICATIONS = [

  // ── IT · CLOUD · DEVOPS ───────────────────────────────
  {
    id: 'aws-saa',
    name: 'AWS Solutions Architect Associate',
    avgCost: 25000, avgHike: 35, timeMonths: 3,
    demand: 'Very High',
    link: 'https://aws.amazon.com/certification/certified-solutions-architect-associate/',
    affiliate: false,
    tags: ['Cloud', 'Backend', 'DevOps'], domain: 'tech',
    forWho: 'Mid-level engineers moving into cloud/architecture roles',
  },
  {
    id: 'aws-pro',
    name: 'AWS Solutions Architect Professional',
    avgCost: 35000, avgHike: 45, timeMonths: 5,
    demand: 'High',
    link: 'https://aws.amazon.com/certification/certified-solutions-architect-professional/',
    affiliate: false,
    tags: ['Cloud', 'Architecture', 'Senior'], domain: 'tech',
    forWho: 'Senior engineers targeting architect or principal roles',
  },
  {
    id: 'aws-devops',
    name: 'AWS DevOps Engineer Professional',
    avgCost: 35000, avgHike: 40, timeMonths: 4,
    demand: 'High',
    link: 'https://aws.amazon.com/certification/certified-devops-engineer-professional/',
    affiliate: false,
    tags: ['DevOps', 'Cloud', 'CI/CD'], domain: 'tech',
    forWho: 'DevOps engineers wanting AWS-specific senior roles',
  },
  {
    id: 'azure-fundamentals',
    name: 'Azure Fundamentals (AZ-900)',
    avgCost: 12000, avgHike: 20, timeMonths: 2,
    demand: 'Very High',
    link: 'https://learn.microsoft.com/certifications/azure-fundamentals/',
    affiliate: false,
    tags: ['Cloud', 'Microsoft', 'Entry-level'], domain: 'tech',
    forWho: 'Beginners and freshers entering cloud computing',
  },
  {
    id: 'azure-developer',
    name: 'Azure Developer Associate (AZ-204)',
    avgCost: 20000, avgHike: 32, timeMonths: 3,
    demand: 'High',
    link: 'https://learn.microsoft.com/certifications/azure-developer/',
    affiliate: false,
    tags: ['Cloud', 'Microsoft', 'Development'], domain: 'tech',
    forWho: 'Developers working on Azure-based applications',
  },
  {
    id: 'azure-architect',
    name: 'Azure Solutions Architect Expert (AZ-305)',
    avgCost: 30000, avgHike: 42, timeMonths: 5,
    demand: 'High',
    link: 'https://learn.microsoft.com/certifications/azure-solutions-architect/',
    affiliate: false,
    tags: ['Cloud', 'Architecture', 'Microsoft'], domain: 'tech',
    forWho: 'Senior engineers targeting Azure architect roles',
  },
  {
    id: 'gcp-ace',
    name: 'Google Cloud Associate Cloud Engineer',
    avgCost: 18000, avgHike: 30, timeMonths: 3,
    demand: 'High',
    link: 'https://cloud.google.com/certification/cloud-engineer',
    affiliate: false,
    tags: ['Cloud', 'Google', 'DevOps'], domain: 'tech',
    forWho: 'Engineers deploying and managing GCP infrastructure',
  },
  {
    id: 'gcp-pro-architect',
    name: 'Google Cloud Professional Architect',
    avgCost: 25000, avgHike: 40, timeMonths: 4,
    demand: 'High',
    link: 'https://cloud.google.com/certification/cloud-architect',
    affiliate: false,
    tags: ['Cloud', 'Google', 'Architecture'], domain: 'tech',
    forWho: 'Senior engineers targeting GCP architect roles',
  },
  {
    id: 'kubernetes',
    name: 'CKA Certified Kubernetes Administrator',
    avgCost: 30000, avgHike: 40, timeMonths: 4,
    demand: 'High',
    link: 'https://training.linuxfoundation.org/certification/certified-kubernetes-administrator-cka/',
    affiliate: false,
    tags: ['DevOps', 'Cloud', 'Containers'], domain: 'tech',
    forWho: 'Backend/DevOps engineers with 2+ yrs wanting infra roles',
  },
  {
    id: 'ckad',
    name: 'CKAD Certified Kubernetes Application Developer',
    avgCost: 28000, avgHike: 35, timeMonths: 3,
    demand: 'High',
    link: 'https://training.linuxfoundation.org/certification/certified-kubernetes-application-developer-ckad/',
    affiliate: false,
    tags: ['DevOps', 'Kubernetes', 'Containers'], domain: 'tech',
    forWho: 'Developers building and deploying apps on Kubernetes',
  },
  {
    id: 'docker-dca',
    name: 'Docker Certified Associate',
    avgCost: 25000, avgHike: 30, timeMonths: 2,
    demand: 'Medium',
    link: 'https://training.mirantis.com/certification/dca-certification-exam/',
    affiliate: false,
    tags: ['DevOps', 'Containers', 'Docker'], domain: 'tech',
    forWho: 'DevOps engineers standardising on container workflows',
  },
  {
    id: 'terraform-associate',
    name: 'HashiCorp Terraform Associate',
    avgCost: 18000, avgHike: 32, timeMonths: 2,
    demand: 'High',
    link: 'https://developer.hashicorp.com/certifications/infrastructure-automation',
    affiliate: false,
    tags: ['DevOps', 'IaC', 'Cloud'], domain: 'tech',
    forWho: 'DevOps/cloud engineers working with infrastructure as code',
  },
  {
    id: 'linux-lpic1',
    name: 'LPIC-1 Linux Administrator',
    avgCost: 15000, avgHike: 22, timeMonths: 2,
    demand: 'Medium',
    link: 'https://www.lpi.org/our-certifications/lpic-1-overview',
    affiliate: false,
    tags: ['Linux', 'SysAdmin', 'Backend'], domain: 'tech',
    forWho: 'IT professionals moving into Linux sysadmin roles',
  },
  {
    id: 'rhcsa',
    name: 'Red Hat RHCSA',
    avgCost: 35000, avgHike: 28, timeMonths: 3,
    demand: 'Medium',
    link: 'https://www.redhat.com/en/services/certification/rhcsa',
    affiliate: false,
    tags: ['Linux', 'RedHat', 'SysAdmin'], domain: 'tech',
    forWho: 'System administrators working in enterprise Linux environments',
  },
  {
    id: 'rhce',
    name: 'Red Hat RHCE',
    avgCost: 45000, avgHike: 35, timeMonths: 4,
    demand: 'Medium',
    link: 'https://www.redhat.com/en/services/certification/rhce',
    affiliate: false,
    tags: ['Linux', 'RedHat', 'Automation'], domain: 'tech',
    forWho: 'Senior Linux admins targeting automation/Ansible roles',
  },
  {
    id: 'comptia-network',
    name: 'CompTIA Network+',
    avgCost: 20000, avgHike: 20, timeMonths: 2,
    demand: 'Medium',
    link: 'https://www.comptia.org/certifications/network',
    affiliate: false,
    tags: ['Networking', 'IT', 'Entry-level'], domain: 'tech',
    forWho: 'IT professionals entering networking roles',
  },
  {
    id: 'comptia-security',
    name: 'CompTIA Security+',
    avgCost: 35000, avgHike: 32, timeMonths: 3,
    demand: 'High',
    link: 'https://www.comptia.org/certifications/security',
    affiliate: false,
    tags: ['Security', 'IT', 'Entry-level'], domain: 'cybersecurity',
    forWho: 'IT professionals moving into cybersecurity',
  },
  {
    id: 'java-ocp',
    name: 'Oracle Java SE Professional (OCP)',
    avgCost: 22000, avgHike: 25, timeMonths: 3,
    demand: 'Medium',
    link: 'https://education.oracle.com/oracle-certified-professional-java-se-17-developer/pexam_1Z0-829',
    affiliate: false,
    tags: ['Java', 'Backend', 'Programming'], domain: 'tech',
    forWho: 'Java developers wanting formal validation and senior roles',
  },
  {
    id: 'microsoft-azure-data',
    name: 'Azure Data Engineer Associate (DP-203)',
    avgCost: 22000, avgHike: 35, timeMonths: 3,
    demand: 'High',
    link: 'https://learn.microsoft.com/certifications/azure-data-engineer/',
    affiliate: false,
    tags: ['Data Engineering', 'Azure', 'Cloud'], domain: 'data',
    forWho: 'Data engineers building pipelines on Azure',
  },

  // ── DATA SCIENCE · AI · ML ────────────────────────────
  {
    id: 'gcp-data',
    name: 'Google Data Analytics Certificate',
    avgCost: 18000, avgHike: 28, timeMonths: 4,
    demand: 'High',
    link: 'https://grow.google/certificates/data-analytics/',
    affiliate: false,
    tags: ['Data', 'Analytics', 'Entry-level'], domain: 'data',
    forWho: 'Career switchers and freshers entering data analytics',
  },
  {
    id: 'tensorflow',
    name: 'TensorFlow Developer Certificate',
    avgCost: 20000, avgHike: 45, timeMonths: 5,
    demand: 'Medium',
    link: 'https://www.tensorflow.org/certificate',
    affiliate: false,
    tags: ['ML', 'AI', 'Python'], domain: 'data',
    forWho: 'Python developers transitioning into ML/AI engineering',
  },
  {
    id: 'ibm-data-science',
    name: 'IBM Data Science Professional Certificate',
    avgCost: 15000, avgHike: 30, timeMonths: 5,
    demand: 'High',
    link: 'https://www.coursera.org/professional-certificates/ibm-data-science',
    affiliate: false,
    tags: ['Data Science', 'Python', 'ML'], domain: 'data',
    forWho: 'Analysts and engineers wanting a structured data science credential',
  },
  {
    id: 'tableau',
    name: 'Tableau Desktop Specialist',
    avgCost: 25000, avgHike: 22, timeMonths: 2,
    demand: 'High',
    link: 'https://www.tableau.com/learn/certification/desktop-specialist',
    affiliate: false,
    tags: ['Data', 'Visualization', 'Analytics'], domain: 'data',
    forWho: 'Business analysts moving into data viz roles',
  },
  {
    id: 'power-bi-da100',
    name: 'Microsoft Power BI Data Analyst (PL-300)',
    avgCost: 18000, avgHike: 25, timeMonths: 2,
    demand: 'Very High',
    link: 'https://learn.microsoft.com/certifications/power-bi-data-analyst-associate/',
    affiliate: false,
    tags: ['Data', 'Power BI', 'Analytics', 'Microsoft'], domain: 'data',
    forWho: 'Business analysts in Microsoft-stack companies',
  },
  {
    id: 'databricks-associate',
    name: 'Databricks Certified Associate Developer',
    avgCost: 25000, avgHike: 38, timeMonths: 3,
    demand: 'High',
    link: 'https://www.databricks.com/learn/certification',
    affiliate: false,
    tags: ['Spark', 'Data Engineering', 'Big Data'], domain: 'data',
    forWho: 'Data engineers working with Spark and lakehouse architectures',
  },
  {
    id: 'snowflake-core',
    name: 'Snowflake SnowPro Core',
    avgCost: 22000, avgHike: 32, timeMonths: 2,
    demand: 'High',
    link: 'https://learn.snowflake.com/en/certifications/',
    affiliate: false,
    tags: ['Data Warehouse', 'Cloud', 'SQL'], domain: 'data',
    forWho: 'Data engineers and analysts on cloud data warehouse stacks',
  },
  {
    id: 'dbt-analytics',
    name: 'dbt Analytics Engineering Certification',
    avgCost: 18000, avgHike: 30, timeMonths: 2,
    demand: 'Medium',
    link: 'https://www.getdbt.com/certifications',
    affiliate: false,
    tags: ['Analytics Engineering', 'SQL', 'Data'], domain: 'data',
    forWho: 'Analytics engineers and SQL-heavy data professionals',
  },
  {
    id: 'deeplearning-ai',
    name: 'DeepLearning.AI Deep Learning Specialization',
    avgCost: 14000, avgHike: 40, timeMonths: 4,
    demand: 'Medium',
    link: 'https://www.deeplearning.ai/courses/deep-learning-specialization/',
    affiliate: false,
    tags: ['Deep Learning', 'AI', 'Neural Networks'], domain: 'data',
    forWho: 'ML engineers specialising in deep learning and neural networks',
  },
  {
    id: 'aws-ml-specialty',
    name: 'AWS Machine Learning Specialty',
    avgCost: 35000, avgHike: 42, timeMonths: 4,
    demand: 'High',
    link: 'https://aws.amazon.com/certification/certified-machine-learning-specialty/',
    affiliate: false,
    tags: ['ML', 'AWS', 'Cloud AI'], domain: 'data',
    forWho: 'ML engineers deploying models on AWS infrastructure',
  },
  {
    id: 'gcp-professional-ml',
    name: 'Google Cloud Professional ML Engineer',
    avgCost: 28000, avgHike: 44, timeMonths: 4,
    demand: 'High',
    link: 'https://cloud.google.com/certification/machine-learning-engineer',
    affiliate: false,
    tags: ['ML', 'GCP', 'Cloud AI'], domain: 'data',
    forWho: 'ML engineers building production models on GCP',
  },

  // ── CYBERSECURITY ─────────────────────────────────────
  {
    id: 'ceh',
    name: 'Certified Ethical Hacker (CEH)',
    avgCost: 50000, avgHike: 38, timeMonths: 4,
    demand: 'High',
    link: 'https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/',
    affiliate: false,
    tags: ['Security', 'Hacking', 'Penetration Testing'], domain: 'cybersecurity',
    forWho: 'Network/security engineers targeting offensive security roles',
  },
  {
    id: 'cissp',
    name: 'CISSP',
    avgCost: 60000, avgHike: 45, timeMonths: 6,
    demand: 'High',
    link: 'https://www.isc2.org/Certifications/CISSP',
    affiliate: false,
    tags: ['Security', 'Management', 'Senior'], domain: 'cybersecurity',
    forWho: 'Senior security professionals targeting CISO/head of security roles',
  },
  {
    id: 'oscp',
    name: 'OSCP Offensive Security Certified Professional',
    avgCost: 95000, avgHike: 55, timeMonths: 6,
    demand: 'High',
    link: 'https://www.offsec.com/courses/pen-200/',
    affiliate: false,
    tags: ['Penetration Testing', 'Offensive Security', 'Advanced'], domain: 'cybersecurity',
    forWho: 'Security professionals targeting senior pentesting roles',
  },
  {
    id: 'cism',
    name: 'CISM Certified Information Security Manager',
    avgCost: 55000, avgHike: 38, timeMonths: 5,
    demand: 'High',
    link: 'https://www.isaca.org/credentialing/cism',
    affiliate: false,
    tags: ['Security Management', 'GRC', 'Senior'], domain: 'cybersecurity',
    forWho: 'Security managers targeting GRC and management tracks',
  },
  {
    id: 'cisa',
    name: 'CISA Certified Information Systems Auditor',
    avgCost: 50000, avgHike: 32, timeMonths: 5,
    demand: 'Medium',
    link: 'https://www.isaca.org/credentialing/cisa',
    affiliate: false,
    tags: ['Audit', 'IT Governance', 'Security'], domain: 'cybersecurity',
    forWho: 'IT auditors and GRC professionals in banking and consulting',
  },
  {
    id: 'comptia-cysa',
    name: 'CompTIA CySA+ (Cybersecurity Analyst)',
    avgCost: 30000, avgHike: 28, timeMonths: 3,
    demand: 'Medium',
    link: 'https://www.comptia.org/certifications/cybersecurity-analyst',
    affiliate: false,
    tags: ['SOC', 'Threat Analysis', 'Security'], domain: 'cybersecurity',
    forWho: 'Security analysts working in SOC environments',
  },
  {
    id: 'aws-security-specialty',
    name: 'AWS Security Specialty',
    avgCost: 35000, avgHike: 38, timeMonths: 4,
    demand: 'High',
    link: 'https://aws.amazon.com/certification/certified-security-specialty/',
    affiliate: false,
    tags: ['Cloud Security', 'AWS', 'Security'], domain: 'cybersecurity',
    forWho: 'Security engineers specialising in cloud infrastructure security',
  },

  // ── FINANCE ───────────────────────────────────────────
  {
    id: 'ca-india',
    name: 'CA (Chartered Accountant) — ICAI',
    avgCost: 80000, avgHike: 60, timeMonths: 48,
    demand: 'Very High',
    link: 'https://www.icai.org/',
    affiliate: false,
    tags: ['Accounting', 'Audit', 'Tax', 'Senior'], domain: 'finance',
    forWho: 'Commerce graduates targeting Big 4, CFO track, or own practice',
  },
  {
    id: 'cfa-l1',
    name: 'CFA Level 1',
    avgCost: 60000, avgHike: 35, timeMonths: 6,
    demand: 'High',
    link: 'https://www.cfainstitute.org/en/programs/cfa',
    affiliate: false,
    tags: ['Finance', 'Investment', 'Banking'], domain: 'finance',
    forWho: 'Finance/banking professionals targeting investment roles',
  },
  {
    id: 'cfa-l2',
    name: 'CFA Level 2',
    avgCost: 65000, avgHike: 45, timeMonths: 8,
    demand: 'High',
    link: 'https://www.cfainstitute.org/en/programs/cfa',
    affiliate: false,
    tags: ['Finance', 'Investment Analysis', 'Banking'], domain: 'finance',
    forWho: 'CFA L1 holders building towards full charter',
  },
  {
    id: 'frm',
    name: 'FRM Financial Risk Manager',
    avgCost: 70000, avgHike: 40, timeMonths: 8,
    demand: 'High',
    link: 'https://www.garp.org/frm',
    affiliate: false,
    tags: ['Risk Management', 'Banking', 'Finance'], domain: 'finance',
    forWho: 'Finance professionals targeting risk management in banking/insurance',
  },
  {
    id: 'fmva',
    name: 'FMVA Financial Modeling & Valuation Analyst',
    avgCost: 20000, avgHike: 28, timeMonths: 3,
    demand: 'High',
    link: 'https://corporatefinanceinstitute.com/certifications/financial-modeling-valuation-analyst-fmva/',
    affiliate: false,
    tags: ['Finance', 'Modeling', 'Excel'], domain: 'finance',
    forWho: 'Finance graduates and analysts wanting valuation skills',
  },
  {
    id: 'cpa-us',
    name: 'US CPA (Certified Public Accountant)',
    avgCost: 150000, avgHike: 55, timeMonths: 12,
    demand: 'High',
    link: 'https://www.aicpa-cima.com/certifications/certified-public-accountant',
    affiliate: false,
    tags: ['Accounting', 'US Finance', 'Audit'], domain: 'finance',
    forWho: 'CAs and finance professionals targeting US/Big 4 global roles',
  },
  {
    id: 'acca',
    name: 'ACCA (Association of Chartered Certified Accountants)',
    avgCost: 200000, avgHike: 50, timeMonths: 24,
    demand: 'High',
    link: 'https://www.accaglobal.com',
    affiliate: false,
    tags: ['Accounting', 'International', 'Finance'], domain: 'finance',
    forWho: 'Finance professionals targeting global accounting and audit roles',
  },
  {
    id: 'sebi-nism',
    name: 'NISM Series VIII — Equity Derivatives',
    avgCost: 5000, avgHike: 20, timeMonths: 1,
    demand: 'High',
    link: 'https://www.nism.ac.in/',
    affiliate: false,
    tags: ['Stock Market', 'Derivatives', 'SEBI'], domain: 'finance',
    forWho: 'Anyone entering stock broking, wealth management, or trading',
  },
  {
    id: 'cfp-india',
    name: 'CFP Certified Financial Planner — India',
    avgCost: 35000, avgHike: 30, timeMonths: 6,
    demand: 'Medium',
    link: 'https://www.fpsb.in/',
    affiliate: false,
    tags: ['Wealth Management', 'Financial Planning', 'Retail'], domain: 'finance',
    forWho: 'Bankers and financial advisors moving into wealth management',
  },

  // ── MANAGEMENT · PROJECT ──────────────────────────────
  {
    id: 'pmp',
    name: 'PMP Project Management Professional',
    avgCost: 55000, avgHike: 30, timeMonths: 6,
    demand: 'High',
    link: 'https://www.pmi.org/certifications/project-management-pmp',
    affiliate: false,
    tags: ['Management', 'Leadership', 'Senior'], domain: 'management',
    forWho: 'Project leads with 3+ yrs targeting senior PM roles',
  },
  {
    id: 'agile-scrum',
    name: 'Certified Scrum Master (CSM)',
    avgCost: 40000, avgHike: 28, timeMonths: 1,
    demand: 'Very High',
    link: 'https://www.scrumalliance.org/get-certified/scrum-master-track/certified-scrummaster',
    affiliate: false,
    tags: ['Agile', 'Scrum', 'Management'], domain: 'management',
    forWho: 'Team leads moving into agile delivery roles',
  },
  {
    id: 'safe-agilist',
    name: 'SAFe Agilist (SA)',
    avgCost: 45000, avgHike: 25, timeMonths: 1,
    demand: 'Medium',
    link: 'https://scaledagile.com/training/leading-safe/',
    affiliate: false,
    tags: ['SAFe', 'Agile', 'Enterprise'], domain: 'management',
    forWho: 'Scrum Masters and PMs working in large enterprise agile setups',
  },
  {
    id: 'prince2',
    name: 'PRINCE2 Foundation',
    avgCost: 30000, avgHike: 22, timeMonths: 2,
    demand: 'Medium',
    link: 'https://www.axelos.com/certifications/propath/prince-2-project-management',
    affiliate: false,
    tags: ['Project Management', 'PRINCE2', 'UK-standard'], domain: 'management',
    forWho: 'PMs in IT services companies targeting UK/EU clients',
  },
  {
    id: 'capm',
    name: 'CAPM Certified Associate PM',
    avgCost: 25000, avgHike: 18, timeMonths: 2,
    demand: 'Medium',
    link: 'https://www.pmi.org/certifications/certified-associate-capm',
    affiliate: false,
    tags: ['Project Management', 'Entry-level', 'PMI'], domain: 'management',
    forWho: 'Freshers and junior PMs wanting PMI credentials',
  },
  {
    id: 'google-pm',
    name: 'Google Project Management Certificate',
    avgCost: 12000, avgHike: 20, timeMonths: 6,
    demand: 'High',
    link: 'https://grow.google/certificates/project-management/',
    affiliate: false,
    tags: ['Business', 'Project Mgmt', 'Entry-level'], domain: 'business',
    forWho: 'Freshers and ops professionals entering PM roles',
  },

  // ── BUSINESS · OPERATIONS ─────────────────────────────
  {
    id: 'six-sigma-green',
    name: 'Six Sigma Green Belt',
    avgCost: 30000, avgHike: 25, timeMonths: 3,
    demand: 'Medium',
    link: 'https://asq.org/cert/six-sigma-green-belt',
    affiliate: false,
    tags: ['Operations', 'Quality', 'Business'], domain: 'business',
    forWho: 'Ops/quality professionals in manufacturing or supply chain',
  },
  {
    id: 'six-sigma-black',
    name: 'Six Sigma Black Belt',
    avgCost: 55000, avgHike: 35, timeMonths: 6,
    demand: 'Medium',
    link: 'https://asq.org/cert/six-sigma-black-belt',
    affiliate: false,
    tags: ['Operations', 'Quality', 'Senior'], domain: 'business',
    forWho: 'Senior ops professionals targeting head of quality roles',
  },
  {
    id: 'apics-cscp',
    name: 'APICS CSCP Supply Chain',
    avgCost: 55000, avgHike: 28, timeMonths: 5,
    demand: 'Medium',
    link: 'https://www.ascm.org/certifications/cscp/',
    affiliate: false,
    tags: ['Supply Chain', 'Operations', 'Logistics'], domain: 'business',
    forWho: 'Ops/logistics professionals targeting supply chain management',
  },
  {
    id: 'apics-cpim',
    name: 'APICS CPIM Production & Inventory Management',
    avgCost: 45000, avgHike: 25, timeMonths: 4,
    demand: 'Medium',
    link: 'https://www.ascm.org/certifications/cpim/',
    affiliate: false,
    tags: ['Supply Chain', 'Manufacturing', 'Inventory'], domain: 'business',
    forWho: 'Manufacturing and production planning professionals',
  },

  // ── MARKETING ─────────────────────────────────────────
  {
    id: 'google-digital-marketing',
    name: 'Google Digital Marketing & E-commerce',
    avgCost: 8000, avgHike: 22, timeMonths: 3,
    demand: 'High',
    link: 'https://skillshop.google.com/',
    affiliate: false,
    tags: ['Marketing', 'SEO', 'Ads'], domain: 'marketing',
    forWho: 'Freshers and non-tech professionals entering digital marketing',
  },
  {
    id: 'hubspot-marketing',
    name: 'HubSpot Inbound Marketing',
    avgCost: 0, avgHike: 18, timeMonths: 1,
    demand: 'Medium',
    link: 'https://academy.hubspot.com/courses/inbound-marketing',
    affiliate: false,
    tags: ['Marketing', 'Inbound', 'CRM', 'Free'], domain: 'marketing',
    forWho: 'Marketing executives — free and fast',
  },
  {
    id: 'meta-social-media',
    name: 'Meta Social Media Marketing Certificate',
    avgCost: 10000, avgHike: 20, timeMonths: 3,
    demand: 'High',
    link: 'https://www.coursera.org/professional-certificates/facebook-social-media-marketing',
    affiliate: false,
    tags: ['Social Media', 'Facebook Ads', 'Marketing'], domain: 'marketing',
    forWho: 'Marketing professionals specialising in social media and paid ads',
  },
  {
    id: 'google-ads-search',
    name: 'Google Ads Search Certification',
    avgCost: 0, avgHike: 15, timeMonths: 1,
    demand: 'High',
    link: 'https://skillshop.google.com/',
    affiliate: false,
    tags: ['Google Ads', 'PPC', 'Marketing', 'Free'], domain: 'marketing',
    forWho: 'Digital marketers running paid search campaigns',
  },
  {
    id: 'semrush-seo',
    name: 'SEMrush SEO Toolkit Certification',
    avgCost: 0, avgHike: 18, timeMonths: 1,
    demand: 'Medium',
    link: 'https://www.semrush.com/academy/',
    affiliate: false,
    tags: ['SEO', 'Content', 'Marketing', 'Free'], domain: 'marketing',
    forWho: 'Content marketers and SEO specialists',
  },
  {
    id: 'salesforce-marketing-cloud',
    name: 'Salesforce Marketing Cloud Email Specialist',
    avgCost: 25000, avgHike: 28, timeMonths: 2,
    demand: 'Medium',
    link: 'https://trailhead.salesforce.com/credentials/marketingcloudemailspecialist',
    affiliate: false,
    tags: ['CRM', 'Email Marketing', 'Salesforce'], domain: 'marketing',
    forWho: 'CRM and email marketing professionals in enterprise setups',
  },

  // ── HR · PEOPLE OPS ───────────────────────────────────
  {
    id: 'shrm',
    name: 'SHRM-CP Human Resources',
    avgCost: 45000, avgHike: 25, timeMonths: 4,
    demand: 'Medium',
    link: 'https://www.shrm.org/credentials/certification/shrm-cp',
    affiliate: false,
    tags: ['HR', 'People Ops', 'Management'], domain: 'hr',
    forWho: 'HR professionals targeting HRBP roles',
  },
  {
    id: 'phr',
    name: 'PHR Professional in Human Resources',
    avgCost: 40000, avgHike: 22, timeMonths: 4,
    demand: 'Medium',
    link: 'https://www.hrci.org/certifications/individual-certifications/phr',
    affiliate: false,
    tags: ['HR', 'Compliance', 'Operations'], domain: 'hr',
    forWho: 'HR generalists targeting specialist or senior roles',
  },
  {
    id: 'linkedin-recruiter',
    name: 'LinkedIn Recruiter Certification',
    avgCost: 5000, avgHike: 15, timeMonths: 1,
    demand: 'Medium',
    link: 'https://business.linkedin.com/talent-solutions/recruiter',
    affiliate: false,
    tags: ['Recruiting', 'HR', 'Talent Acquisition'], domain: 'hr',
    forWho: 'Recruiters and talent acquisition professionals',
  },

  // ── PRODUCT · UX · DESIGN ─────────────────────────────
  {
    id: 'product-management',
    name: 'Product Management Certification — PM School',
    avgCost: 35000, avgHike: 35, timeMonths: 3,
    demand: 'High',
    link: 'https://www.pmschool.io/',
    affiliate: false,
    tags: ['Product', 'PM', 'Tech', 'Strategy'], domain: 'product',
    forWho: 'Engineers and analysts with 2+ yrs wanting to move into PM',
  },
  {
    id: 'google-ux',
    name: 'Google UX Design Certificate',
    avgCost: 12000, avgHike: 30, timeMonths: 6,
    demand: 'Medium',
    link: 'https://grow.google/certificates/ux-design/',
    affiliate: false,
    tags: ['UX', 'Design', 'Product'], domain: 'design',
    forWho: 'Career switchers entering UX/product design',
  },
  {
    id: 'interaction-design',
    name: 'Interaction Design Foundation UX Certificate',
    avgCost: 12000, avgHike: 28, timeMonths: 6,
    demand: 'Medium',
    link: 'https://www.interaction-design.org/courses',
    affiliate: false,
    tags: ['UX', 'Interaction Design', 'Product'], domain: 'design',
    forWho: 'Designers formalising their UX knowledge for senior roles',
  },
  {
    id: 'figma-professional',
    name: 'Figma Professional Designer Certification',
    avgCost: 8000, avgHike: 20, timeMonths: 1,
    demand: 'Medium',
    link: 'https://www.figma.com/certification/',
    affiliate: false,
    tags: ['UI Design', 'Figma', 'Visual Design'], domain: 'design',
    forWho: 'UI/UX designers standardising on Figma workflows',
  },

  // ── MEDICAL · HEALTHCARE ──────────────────────────────
  {
    id: 'usmle-step1',
    name: 'USMLE Step 1',
    avgCost: 120000, avgHike: 80, timeMonths: 12,
    demand: 'High',
    link: 'https://www.usmle.org/',
    affiliate: false,
    tags: ['Medical', 'USMLE', 'US License'], domain: 'medical',
    forWho: 'MBBS graduates targeting residency in the United States',
  },
  {
    id: 'usmle-step2',
    name: 'USMLE Step 2 CK',
    avgCost: 130000, avgHike: 80, timeMonths: 8,
    demand: 'High',
    link: 'https://www.usmle.org/',
    affiliate: false,
    tags: ['Medical', 'USMLE', 'Clinical Knowledge'], domain: 'medical',
    forWho: 'USMLE Step 1 holders progressing towards US residency match',
  },
  {
    id: 'plab',
    name: 'PLAB (UK Medical Licensing)',
    avgCost: 80000, avgHike: 70, timeMonths: 6,
    demand: 'High',
    link: 'https://www.gmc-uk.org/registration-and-licensing/join-the-register/plab',
    affiliate: false,
    tags: ['Medical', 'UK License', 'NHS'], domain: 'medical',
    forWho: 'Indian MBBS doctors targeting NHS UK practice',
  },
  {
    id: 'dnb-india',
    name: 'DNB Diplomate of National Board — India',
    avgCost: 200000, avgHike: 60, timeMonths: 36,
    demand: 'Very High',
    link: 'https://www.natboard.edu.in/',
    affiliate: false,
    tags: ['Medical Specialty', 'DNB', 'India'], domain: 'medical',
    forWho: 'MBBS doctors pursuing postgraduate specialisation in India',
  },
  {
    id: 'fellow-nbe',
    name: 'Fellowship NBE (FNB) — Super Speciality',
    avgCost: 100000, avgHike: 50, timeMonths: 24,
    demand: 'High',
    link: 'https://www.natboard.edu.in/',
    affiliate: false,
    tags: ['Medical', 'Super Speciality', 'Fellowship'], domain: 'medical',
    forWho: 'DNB/MD holders pursuing super speciality fellowship training',
  },
  {
    id: 'nursing-ielts-uk',
    name: 'NMC OET — Nursing UK Registration',
    avgCost: 25000, avgHike: 60, timeMonths: 3,
    demand: 'High',
    link: 'https://www.nmc.org.uk/',
    affiliate: false,
    tags: ['Nursing', 'UK License', 'OET'], domain: 'medical',
    forWho: 'Indian BSc Nursing graduates targeting NHS UK placements',
  },
  {
    id: 'clinical-research-acrp',
    name: 'ACRP Certified Clinical Research Associate',
    avgCost: 40000, avgHike: 35, timeMonths: 4,
    demand: 'Medium',
    link: 'https://acrpnet.org/certifications/',
    affiliate: false,
    tags: ['Clinical Research', 'Pharma', 'CRA'], domain: 'medical',
    forWho: 'Life sciences graduates entering clinical trials and pharma CRO roles',
  },
  {
    id: 'hospital-management',
    name: 'Healthcare Management Certificate — AHPI',
    avgCost: 30000, avgHike: 30, timeMonths: 3,
    demand: 'Medium',
    link: 'https://www.ahpi.in/',
    affiliate: false,
    tags: ['Hospital Management', 'Healthcare Admin'], domain: 'medical',
    forWho: 'Healthcare administrators targeting hospital management roles',
  },

  // ── LAW ───────────────────────────────────────────────
  {
    id: 'bar-india',
    name: 'Bar Council Enrollment — All India Bar Exam',
    avgCost: 10000, avgHike: 40, timeMonths: 1,
    demand: 'Very High',
    link: 'https://www.barcouncilofindia.org/',
    affiliate: false,
    tags: ['Law', 'Bar Exam', 'Litigation'], domain: 'law',
    forWho: 'LLB graduates required to enroll before practice in India',
  },
  {
    id: 'cs-india',
    name: 'Company Secretary (CS) — ICSI',
    avgCost: 60000, avgHike: 45, timeMonths: 24,
    demand: 'High',
    link: 'https://www.icsi.edu/',
    affiliate: false,
    tags: ['Corporate Law', 'CS', 'Compliance'], domain: 'law',
    forWho: 'Commerce/law graduates targeting corporate secretary roles',
  },
  {
    id: 'ip-patent-agent',
    name: 'Indian Patent Agent Examination',
    avgCost: 15000, avgHike: 40, timeMonths: 6,
    demand: 'Medium',
    link: 'https://ipindia.gov.in/',
    affiliate: false,
    tags: ['Intellectual Property', 'Patents', 'Law'], domain: 'law',
    forWho: 'Science/engineering graduates targeting IP law careers',
  },
  {
    id: 'gdpr-practitioner',
    name: 'GDPR Practitioner Certificate',
    avgCost: 25000, avgHike: 28, timeMonths: 2,
    demand: 'Medium',
    link: 'https://www.bcs.org/qualifications-and-certifications/certifications-for-professionals/data-protection-and-gdpr-certifications/',
    affiliate: false,
    tags: ['Privacy Law', 'GDPR', 'Compliance'], domain: 'law',
    forWho: 'Legal and compliance professionals in tech/global companies',
  },
  {
    id: 'llm-international',
    name: 'LLM (Master of Laws) — International Arbitration',
    avgCost: 500000, avgHike: 55, timeMonths: 12,
    demand: 'Medium',
    link: 'https://www.lawschool.cornell.edu/',
    affiliate: false,
    tags: ['International Law', 'Arbitration', 'LLM'], domain: 'law',
    forWho: 'Senior lawyers targeting international arbitration and M&A practices',
  },

  // ── ARCHITECTURE ──────────────────────────────────────
  {
    id: 'council-architecture',
    name: 'Council of Architecture Registration — India',
    avgCost: 5000, avgHike: 30, timeMonths: 1,
    demand: 'Very High',
    link: 'https://www.coa.gov.in/',
    affiliate: false,
    tags: ['Architecture', 'Registration', 'India'], domain: 'architecture',
    forWho: 'B.Arch graduates — mandatory before practising architecture in India',
  },
  {
    id: 'leed-green-associate',
    name: 'LEED Green Associate',
    avgCost: 20000, avgHike: 25, timeMonths: 2,
    demand: 'Medium',
    link: 'https://www.usgbc.org/credentials/leed-green-associate',
    affiliate: false,
    tags: ['Sustainable Design', 'LEED', 'Green Building'], domain: 'architecture',
    forWho: 'Architects and civil engineers targeting green building projects',
  },
  {
    id: 'leed-ap-bd-c',
    name: 'LEED AP Building Design + Construction',
    avgCost: 35000, avgHike: 35, timeMonths: 3,
    demand: 'Medium',
    link: 'https://www.usgbc.org/credentials/leed-ap-building-design-construction',
    affiliate: false,
    tags: ['Sustainable Design', 'LEED AP', 'Construction'], domain: 'architecture',
    forWho: 'Senior architects targeting LEED certified project leadership',
  },
  {
    id: 'revit-autodesk',
    name: 'Autodesk Certified Professional — Revit',
    avgCost: 15000, avgHike: 22, timeMonths: 2,
    demand: 'High',
    link: 'https://www.autodesk.com/certification/overview',
    affiliate: false,
    tags: ['BIM', 'Revit', 'Architecture Software'], domain: 'architecture',
    forWho: 'Architects and draftsmen upskilling in BIM/Revit workflows',
  },
  {
    id: 'riba-part3',
    name: 'RIBA Part 3 — UK Architecture License',
    avgCost: 300000, avgHike: 60, timeMonths: 12,
    demand: 'Medium',
    link: 'https://www.architecture.com/education-cpd-and-careers/riba-part-3',
    affiliate: false,
    tags: ['Architecture', 'UK License', 'RIBA'], domain: 'architecture',
    forWho: 'Indian architects with Part 1/2 equivalent targeting UK ARB registration',
  },

  // ── CIVIL · MECHANICAL · ELECTRICAL ENGINEERING ───────
  {
    id: 'pe-license-us',
    name: 'PE License — Professional Engineer (US)',
    avgCost: 50000, avgHike: 50, timeMonths: 12,
    demand: 'Medium',
    link: 'https://ncees.org/engineering/pe/',
    affiliate: false,
    tags: ['Civil Engineering', 'PE License', 'US'], domain: 'engineering',
    forWho: 'Indian engineers with US work permits targeting licensed PE roles',
  },
  {
    id: 'gate',
    name: 'GATE — Graduate Aptitude Test in Engineering',
    avgCost: 2000, avgHike: 40, timeMonths: 6,
    demand: 'Very High',
    link: 'https://gate.iitb.ac.in/',
    affiliate: false,
    tags: ['Engineering', 'GATE', 'PSU', 'MTech'], domain: 'engineering',
    forWho: 'Engineering graduates targeting PSU jobs or M.Tech/MS admissions',
  },
  {
    id: 'pmp-construction',
    name: 'PMP — Construction Project Management',
    avgCost: 55000, avgHike: 32, timeMonths: 6,
    demand: 'Medium',
    link: 'https://www.pmi.org/certifications/project-management-pmp',
    affiliate: false,
    tags: ['Construction', 'Project Management', 'Civil'], domain: 'engineering',
    forWho: 'Civil/construction engineers targeting project management tracks',
  },
  {
    id: 'autocad-professional',
    name: 'Autodesk AutoCAD Certified Professional',
    avgCost: 12000, avgHike: 20, timeMonths: 2,
    demand: 'High',
    link: 'https://www.autodesk.com/certification/overview',
    affiliate: false,
    tags: ['CAD', 'Engineering Drawing', 'Design'], domain: 'engineering',
    forWho: 'Mechanical/civil engineers and draftsmen upskilling in CAD',
  },
  {
    id: 'six-sigma-manufacturing',
    name: 'Six Sigma Black Belt — Manufacturing',
    avgCost: 55000, avgHike: 35, timeMonths: 6,
    demand: 'Medium',
    link: 'https://asq.org/cert/six-sigma-black-belt',
    affiliate: false,
    tags: ['Manufacturing', 'Quality', 'Operations'], domain: 'engineering',
    forWho: 'Manufacturing engineers targeting quality/ops leadership roles',
  },
  {
    id: 'iiot-industrial',
    name: 'Industrial IoT Certification — Coursera/IIT',
    avgCost: 15000, avgHike: 30, timeMonths: 3,
    demand: 'Medium',
    link: 'https://www.coursera.org/learn/industrial-iot',
    affiliate: false,
    tags: ['IIoT', 'Automation', 'Industry 4.0'], domain: 'engineering',
    forWho: 'Mechanical/electrical engineers transitioning into smart manufacturing',
  },
  {
    id: 'solar-energy-engineer',
    name: 'NABCEP Solar PV Installation Professional',
    avgCost: 30000, avgHike: 35, timeMonths: 3,
    demand: 'High',
    link: 'https://www.nabcep.org/',
    affiliate: false,
    tags: ['Solar', 'Renewable Energy', 'Electrical'], domain: 'engineering',
    forWho: 'Electrical engineers entering India\'s booming solar energy sector',
  },
  {
    id: 'autocad-civil3d',
    name: 'AutoCAD Civil 3D Certified User',
    avgCost: 12000, avgHike: 22, timeMonths: 2,
    demand: 'Medium',
    link: 'https://www.autodesk.com/certification/overview',
    affiliate: false,
    tags: ['Civil Engineering', 'CAD', 'Infrastructure'], domain: 'engineering',
    forWho: 'Civil engineers working on road, highway, and drainage projects',
  },

  // ── GOVERNMENT · PSU · COMPETITIVE ────────────────────
  {
    id: 'upsc-ias',
    name: 'UPSC Civil Services (IAS/IPS/IFS)',
    avgCost: 150000, avgHike: 100, timeMonths: 24,
    demand: 'Very High',
    link: 'https://www.upsc.gov.in/',
    affiliate: false,
    tags: ['Government', 'IAS', 'Civil Services', 'UPSC'], domain: 'government',
    forWho: 'Graduates targeting Indian Administrative/Police/Foreign Service',
  },
  {
    id: 'ssc-cgl',
    name: 'SSC CGL (Staff Selection Commission)',
    avgCost: 5000, avgHike: 30, timeMonths: 6,
    demand: 'Very High',
    link: 'https://ssc.nic.in/',
    affiliate: false,
    tags: ['Government', 'SSC', 'Central Government'], domain: 'government',
    forWho: 'Graduates targeting Group B/C central government positions',
  },
  {
    id: 'ibps-po',
    name: 'IBPS PO — Bank Probationary Officer',
    avgCost: 5000, avgHike: 35, timeMonths: 6,
    demand: 'Very High',
    link: 'https://www.ibps.in/',
    affiliate: false,
    tags: ['Banking', 'Government', 'IBPS'], domain: 'government',
    forWho: 'Graduates targeting public sector bank officer roles',
  },
  {
    id: 'rrb-je',
    name: 'RRB JE — Railway Junior Engineer',
    avgCost: 3000, avgHike: 30, timeMonths: 6,
    demand: 'Very High',
    link: 'https://www.rrbcdg.gov.in/',
    affiliate: false,
    tags: ['Railways', 'Government', 'Engineering'], domain: 'government',
    forWho: 'Diploma/B.Tech engineers targeting Indian Railways technical roles',
  },
  {
    id: 'psu-gate-bhel',
    name: 'GATE — PSU Recruitment (BHEL/ONGC/NTPC)',
    avgCost: 2000, avgHike: 45, timeMonths: 6,
    demand: 'Very High',
    link: 'https://gate.iitb.ac.in/',
    affiliate: false,
    tags: ['PSU', 'GATE', 'Government Engineering'], domain: 'government',
    forWho: 'Engineering graduates targeting BHEL, ONGC, NTPC, IOCL via GATE score',
  },
  {
    id: 'nda',
    name: 'NDA — National Defence Academy',
    avgCost: 3000, avgHike: 50, timeMonths: 6,
    demand: 'High',
    link: 'https://www.upsc.gov.in/examinations/nda-examination',
    affiliate: false,
    tags: ['Defence', 'Army', 'Navy', 'Air Force'], domain: 'government',
    forWho: '12th pass students targeting Indian Army/Navy/Air Force officer roles',
  },
  {
    id: 'state-psc',
    name: 'State PSC (KPSC/MPSC/TNPSC/UPPSC)',
    avgCost: 10000, avgHike: 35, timeMonths: 12,
    demand: 'Very High',
    link: 'https://kpsc.kar.nic.in/',
    affiliate: false,
    tags: ['State Government', 'PSC', 'Group A/B'], domain: 'government',
    forWho: 'Graduates targeting state government gazetted officer positions',
  },

  // ── MBA · MANAGEMENT SPECIALISATIONS ─────────────────
  {
    id: 'cat-iim',
    name: 'CAT — IIM MBA Entrance',
    avgCost: 30000, avgHike: 80, timeMonths: 6,
    demand: 'Very High',
    link: 'https://iimcat.ac.in/',
    affiliate: false,
    tags: ['MBA', 'IIM', 'CAT', 'Management'], domain: 'mba',
    forWho: 'Professionals with 2-5 yrs experience targeting IIM MBA for career acceleration',
  },
  {
    id: 'gmat',
    name: 'GMAT — Global MBA Entrance',
    avgCost: 25000, avgHike: 70, timeMonths: 3,
    demand: 'High',
    link: 'https://www.mba.com/exams/gmat',
    affiliate: false,
    tags: ['MBA', 'GMAT', 'International', 'Management'], domain: 'mba',
    forWho: 'Professionals targeting top global MBA programs (ISB, INSEAD, Wharton)',
  },
  {
    id: 'cma-us',
    name: 'CMA — Certified Management Accountant (US)',
    avgCost: 70000, avgHike: 38, timeMonths: 9,
    demand: 'Medium',
    link: 'https://www.imanet.org/cma-certification',
    affiliate: false,
    tags: ['Management Accounting', 'Finance', 'Strategy'], domain: 'finance',
    forWho: 'Finance managers targeting CFO/strategic finance leadership roles',
  },

  // ── SALESFORCE · CRM ──────────────────────────────────
  {
    id: 'salesforce-admin',
    name: 'Salesforce Certified Administrator',
    avgCost: 20000, avgHike: 30, timeMonths: 2,
    demand: 'High',
    link: 'https://trailhead.salesforce.com/credentials/administrator',
    affiliate: false,
    tags: ['Salesforce', 'CRM', 'Admin'], domain: 'tech',
    forWho: 'IT/ops professionals managing or implementing Salesforce',
  },
  {
    id: 'salesforce-developer',
    name: 'Salesforce Platform Developer I',
    avgCost: 25000, avgHike: 35, timeMonths: 3,
    demand: 'High',
    link: 'https://trailhead.salesforce.com/credentials/platformdeveloperI',
    affiliate: false,
    tags: ['Salesforce', 'CRM', 'Development'], domain: 'tech',
    forWho: 'Developers building custom applications on the Salesforce platform',
  },
  {
    id: 'servicenow-admin',
    name: 'ServiceNow Certified System Administrator',
    avgCost: 22000, avgHike: 28, timeMonths: 2,
    demand: 'High',
    link: 'https://www.servicenow.com/services/training-and-certification.html',
    affiliate: false,
    tags: ['ServiceNow', 'ITSM', 'Enterprise IT'], domain: 'tech',
    forWho: 'ITSM professionals managing enterprise IT service platforms',
  },

  // ── ADDITIONAL HIGH-VALUE ─────────────────────────────
  {
    id: 'pgpm-isb',
    name: 'ISB PGP Certificate Programme',
    avgCost: 300000, avgHike: 65, timeMonths: 12,
    demand: 'High',
    link: 'https://www.isb.edu/en/programmes-executive-education.html',
    affiliate: false,
    tags: ['Executive Education', 'Leadership', 'Senior'], domain: 'mba',
    forWho: 'Senior professionals with 8+ yrs targeting C-suite or general management',
  },
  {
    id: 'blockchain-certified',
    name: 'Certified Blockchain Professional — EC-Council',
    avgCost: 25000, avgHike: 30, timeMonths: 2,
    demand: 'Low',
    link: 'https://www.blockchain-council.org/certifications/certified-blockchain-professional-expert/',
    affiliate: false,
    tags: ['Blockchain', 'Web3', 'Emerging Tech'], domain: 'tech',
    forWho: 'Developers exploring Web3/DeFi roles — still early market in India',
  },
  {
    id: 'pega-csa',
    name: 'Pega Certified System Architect (CSA)',
    avgCost: 20000, avgHike: 28, timeMonths: 2,
    demand: 'Medium',
    link: 'https://academy.pega.com/certification',
    affiliate: false,
    tags: ['Pega', 'BPM', 'Low-Code'], domain: 'tech',
    forWho: 'Developers working on Pega BPM platforms in insurance/banking',
  },
  {
    id: 'sap-basis',
    name: 'SAP Certified Associate — SAP Basis',
    avgCost: 40000, avgHike: 30, timeMonths: 3,
    demand: 'Medium',
    link: 'https://training.sap.com/certification/c_adm_2400-sap-certified-associate---sap-s4hana-system-administration-g/',
    affiliate: false,
    tags: ['SAP', 'ERP', 'Basis'], domain: 'tech',
    forWho: 'IT admins managing SAP landscapes in large enterprises',
  },
  {
    id: 'sap-fico',
    name: 'SAP Certified Application Associate — SAP FICO',
    avgCost: 45000, avgHike: 32, timeMonths: 3,
    demand: 'Medium',
    link: 'https://training.sap.com/',
    affiliate: false,
    tags: ['SAP', 'Finance', 'ERP', 'FICO'], domain: 'finance',
    forWho: 'Finance professionals implementing or managing SAP FICO modules',
  },
  {
    id: 'oracle-cloud-erp',
    name: 'Oracle Cloud ERP Associate',
    avgCost: 35000, avgHike: 30, timeMonths: 3,
    demand: 'Medium',
    link: 'https://education.oracle.com/',
    affiliate: false,
    tags: ['Oracle', 'ERP', 'Cloud Finance'], domain: 'tech',
    forWho: 'Finance/IT professionals implementing Oracle Cloud ERP',
  },
]

// ── CERT DOMAINS ──────────────────────────────────────────────
export const CERT_DOMAINS = [
  { id: 'all',           label: 'All Domains'         },
  { id: 'tech',          label: 'Tech & Cloud'        },
  { id: 'data',          label: 'Data & AI'           },
  { id: 'cybersecurity', label: 'Cybersecurity'       },
  { id: 'management',   label: 'Project Mgmt'        },
  { id: 'business',     label: 'Business & Ops'      },
  { id: 'finance',      label: 'Finance & Accounting' },
  { id: 'marketing',    label: 'Marketing'            },
  { id: 'product',      label: 'Product'              },
  { id: 'design',       label: 'UX & Design'         },
  { id: 'hr',           label: 'HR & People'         },
  { id: 'medical',      label: 'Medical & Health'    },
  { id: 'law',          label: 'Law & Compliance'    },
  { id: 'architecture', label: 'Architecture'        },
  { id: 'engineering',  label: 'Civil/Mech/Elec'     },
  { id: 'government',   label: 'Govt & PSU Exams'    },
  { id: 'mba',          label: 'MBA & Executive'     },
]

// ── GOAL OPTIONS ──────────────────────────────────────────────
export const GOAL_OPTIONS = [
  { id: 'salary-hike',   label: 'Get a salary hike at current job' },
  { id: 'job-switch',    label: 'Switch to a better company' },
  { id: 'career-switch', label: 'Switch to a completely different field' },
  { id: 'first-job',     label: 'Get my first job / fresher offer' },
  { id: 'promotion',     label: 'Get promoted to senior/lead role' },
  { id: 'freelance',     label: 'Start freelancing or consulting' },
  { id: 'abroad',        label: 'Get a job abroad (US/UK/Singapore/UAE)' },
  { id: 'startup',       label: 'Join or start a startup' },
  { id: 'psu-govt',      label: 'Get a PSU or government position' },
  { id: 'higher-study',  label: 'Higher studies (MTech/MBA/MS abroad)' },
]

// ── INDIA CONTEXT ─────────────────────────────────────────────
export const INDIA_CONTEXT = {
  avgEntryLevel: 480000,
  avgMidLevel:   1200000,
  pgRentAnnual:  180000,
  currency:      '₹',
  cities: [
    'Bangalore', 'Hyderabad', 'Pune', 'Mumbai',
    'Delhi NCR', 'Chennai', 'Kolkata', 'Ahmedabad',
  ],
}

// ── GUEST LIMIT ───────────────────────────────────────────────
export const GUEST_FREE_LIMIT = parseInt(import.meta.env.VITE_GUEST_FREE_LIMIT || '3')
